### 1. Write a program to reverse a string.

In [1]:
S ="iit dharwad"
print(S[::-1])

dawrahd tii


### 2. Check if a string is a palindrome.

In [2]:
s1 = S[::-1]
s2 = S
if(s1 == S):
    print("It is palindrome")
else:
    print("It is not a palindrome")

It is not a palindrome


In [3]:
if(s2 == S):
    print("It is palindrome")
else:
    print("It is not a palindrome")

It is palindrome


### 3. Convert a string to uppercase.

In [4]:
s1.upper()

'DAWRAHD TII'

### 4. Convert a string to lowercase.

In [5]:
s1.lower()

'dawrahd tii'

### 5. Count the number of vowels in a string.

In [6]:
count  = 0
for char in S:
    if char in (["a","e","i","o","u"]):
        count = count+1

In [7]:
print(count)

4


### 6. Count the number of consonants in a string.

In [8]:
count1 = 0
count2 = 0

In [9]:
for char in S:
    if char in (["a","e","i","o","u"," "]):
        count2 = 0
    else:
        count1 += 1

In [10]:
print(count1)

6


### 7. Remove all whitespaces from a string.

In [11]:
 S.replace(" ","")

'iitdharwad'

### 8. Find the length of a string without using the `len()` function.

In [12]:
cou = 0
for i in S:
    cou += 1

In [13]:
print (cou)

11


### 9. Check if a string contains a specific word.

In [14]:
word_to_check = "har"
if word_to_check in S:
    print("String contains the word '{}'.".format(word_to_check)) 
else:
    print("String does not contain the word '{}'.".format(word_to_check))

String contains the word 'har'.


### 10. Replace a word in a string with another word.

In [15]:
new_string = S.replace("harwad", "elhi")
print(new_string)

iit delhi


### 11. Count the occurrences of a word in a string.

In [16]:
word_to_count = "i"
count_occurrences = S.count(word_to_count)
print("Occurrences of '{}' in the string: {}".format(word_to_count, count_occurrences))

Occurrences of 'i' in the string: 2


### 12. Find the first occurrence of a word in a string.

In [17]:
first_occurrence_index = S.find(word_to_count)
print("First occurrence of '{}' at index: {}".format(word_to_count, first_occurrence_index)) 

First occurrence of 'i' at index: 0


### 13. Find the last occurrence of a word in a string.

In [18]:
last_occurrence_index = S.rfind(word_to_count)
print("Last occurrence of '{}' at index: {}".format(word_to_count, last_occurrence_index))

Last occurrence of 'i' at index: 1


### 14. Split a string into a list of words.

In [19]:
word_list = S.split()
print(word_list)

['iit', 'dharwad']


### 15. Join a list of words into a string.

In [20]:
list_ = ["IIT","NIT"]
joined_string = " ".join(list_)
print(joined_string)

IIT NIT


### 16. Convert a string where words are separated by spaces to one where words are separated by underscores.

In [21]:
string_with_spaces = "convert string with spaces"
string_with_underscores = string_with_spaces.replace(" ", "_")
print(string_with_underscores)

convert_string_with_spaces


### 17. Check if a string starts with a specific word or phrase.

In [22]:
specific_word = "convert"
if string_with_spaces.startswith(specific_word):
    print("String starts with '{}'.".format(specific_word))  
else:
    print("String does not start with '{}'.".format(specific_word))

String starts with 'convert'.


### 18. Check if a string ends with a specific word or phrase.

In [23]:
specific_word = "spaces"
if string_with_spaces.endswith(specific_word):
    print("String ends with '{}'.".format(specific_word))  # Output: String ends with 'spaces'.
else:
    print("String does not end with '{}'.".format(specific_word))


String ends with 'spaces'.


### 19. Convert a string to title case (e.g., "hello world" to "Hello World").

In [24]:
string_to_title_case = "hello world"
title_case_string = string_to_title_case.title()
print(title_case_string)  

Hello World


### 20. Find the longest word in a string.

In [25]:
words = string_with_spaces.split()
longest_word = max(words, key=len)
print("Longest word:", longest_word) 

Longest word: convert


### 21. Find the shortest word in a string.

In [26]:
shortest_word = min(words, key=len)
print("Shortest word:", shortest_word)

Shortest word: with


### 22. Reverse the order of words in a string.

In [27]:
reversed_words = " ".join(reversed(words))
print(reversed_words)

spaces with string convert


### 23. Check if a string is alphanumeric.

In [28]:
def is_alphanumeric(text):
    # Step 1: Use the isalnum() method to check if the string is alphanumeric.
    return text.isalnum()

# Example usage
text = "Hello123"
result = is_alphanumeric(text)
if result:
    print("The string is alphanumeric.")
else:
    print("The string is not alphanumeric.")

The string is alphanumeric.


### 24. Extract all digits from a string.

In [29]:
def extract_digits(text):
    # Step 1: Initialize an empty string to store the extracted digits.
    digits = ""

    # Step 2: Iterate through each character in the text.
    for char in text:
        # Check if the character is a digit using the isdigit() method.
        if char.isdigit():
            # Append the digit to the digits string.
            digits += char

    # Step 3: Return the extracted digits.
    return digits

# Example usage
text = "Hello123World456"
extracted_digits = extract_digits(text)
print("Extracted digits:", extracted_digits)

Extracted digits: 123456


### 25. Extract all alphabets from a string.

In [30]:
def extract_alphabets(input_string):
    alphabets = ' '.join([char for char in input_string if char.isalpha()])
    return alphabets

# Example input string
input_string = "Hello123World456"
result = extract_alphabets(input_string)
print(result)

H e l l o W o r l d


### 26. Count the number of uppercase letters in a string.

In [31]:
def count_uppercase(input_string):
    uppercase_count = sum(1 for char in input_string if char.isupper())
    return uppercase_count

# Example input string
input_string = "HelloWORLD"
result = count_uppercase(input_string)
print(result)

6


### 27. Count the number of lowercase letters in a string.

In [32]:
def count_lowercase(input_string):
    lowercase_count = sum(1 for char in input_string if char.islower())
    return lowercase_count

# Example input string
input_string = "HelloWORLD"
result = count_lowercase(input_string)
print(result)

4


### 28. Swap the case of each character in a string.

In [33]:
def swap_case(input_string):
    swapped_string = input_string.swapcase()
    return swapped_string

# Example input string
input_string = "HelloWORLD"
result = swap_case(input_string)
print(result)

hELLOworld


### 29. Remove a specific word from a string.

In [34]:
def remove_word(input_string, word_to_remove):
    words = input_string.split()  # Split the input string into a list of words
    filtered_words = [word for word in words if word != word_to_remove]  # Create a new list excluding the word to remove
    modified_string = ' '.join(filtered_words)  # Join the filtered words back into a string
    return modified_string

# Example input string and word to remove
input_string = "Hello world, welcome to the world of programming."
word_to_remove = "world"
result = remove_word(input_string, word_to_remove)
print(result)

Hello world, welcome to the of programming.


### 30. Check if a string is a valid email address.

In [35]:
import re  # Import the regular expression module

def is_valid_email(email):
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'  # Regular expression pattern for a basic email validation
    if re.match(pattern, email):
        return True
    else:
        return False

# Example email addresses
email1 = "example@email.com"
email2 = "invalid-email"
result1 = is_valid_email(email1)
result2 = is_valid_email(email2)
print(result1)
print(result2)

True
False


### 31. Extract the username from an email address string.

In [36]:
def extract_username(email):
    username = email.split('@')[0]  # Split the email address at "@" and take the first part
    return username

# Example email address
email = "example@email.com"
result = extract_username(email)
print(result)

example


### 32. Extract the domain name from an email address string.

In [37]:
def extract_domain(email):
    domain = email.split('@')[1]  # Split the email address at "@" and take the second part
    return domain

# Example email address
email = "example@email.com"
result = extract_domain(email)
print(result)

email.com


### 33. Replace multiple spaces in a string with a single space.

In [38]:
def replace_multiple_spaces(input_string):
    cleaned_string = ' '.join(input_string.split())  # Split the string at spaces and then join using a single space
    return cleaned_string

# Example input string with multiple spaces
input_string = "Hello     world!   How   are   you?"
result = replace_multiple_spaces(input_string)
print(result)

Hello world! How are you?


### 34. Check if a string is a valid URL.

In [39]:
from urllib.parse import urlparse

def is_valid_url(url):
    try:
        result = urlparse(url)
        return all([result.scheme, result.netloc])  # Check if both scheme and netloc are present
    except ValueError:
        return False

# Example URLs
url1 = "https://www.example.com"
url2 = "invalid-url"
result1 = is_valid_url(url1)
result2 = is_valid_url(url2)
print(result1)  # Should print True
print(result2)  # Should print False

True
False


### 35. Extract the protocol (http or https) from a URL string.

In [40]:
def extract_protocol(url):
    # Find the index of the first occurrence of "://"
    protocol_end = url.find("://")

    if protocol_end != -1:
        # Extract the protocol from the URL
        protocol = url[:protocol_end]
        return protocol
    else:
        return None

# Example URL strings
url1 = "https://www.example.com"
url2 = "http://google.com"
url3 = "ftp://ftp.example.com"

# Extract protocols
protocol1 = extract_protocol(url1)
protocol2 = extract_protocol(url2)
protocol3 = extract_protocol(url3)

# Print extracted protocols
print("Protocol 1:", protocol1)
print("Protocol 2:", protocol2)
print("Protocol 3:", protocol3)

Protocol 1: https
Protocol 2: http
Protocol 3: ftp


### 36. Find the frequency of each character in a string.

In [41]:
def character_frequency(input_string):
    frequency = {}  # Create an empty dictionary to store character frequencies

    for char in input_string:
        if char in frequency:
            frequency[char] += 1  # Increment the frequency count if the character is already in the dictionary
        else:
            frequency[char] = 1   # Initialize the frequency count to 1 if the character is not in the dictionary

    return frequency

# Example string
input_str = "hello world"

# Calculate character frequencies
char_freq = character_frequency(input_str)

# Print character frequencies
for char, freq in char_freq.items():
    print(f"Character: '{char}', Frequency: {freq}")

Character: 'h', Frequency: 1
Character: 'e', Frequency: 1
Character: 'l', Frequency: 3
Character: 'o', Frequency: 2
Character: ' ', Frequency: 1
Character: 'w', Frequency: 1
Character: 'r', Frequency: 1
Character: 'd', Frequency: 1


### 37. Remove all punctuation from a string.

In [42]:
import string

def remove_punctuation(input_string):
    # Create a translation table to remove punctuation
    translator = str.maketrans("", "", string.punctuation)

    # Use the translation table to remove punctuation from the input string
    clean_string = input_string.translate(translator)

    return clean_string

# Example string with punctuation
input_str = "Hello, world! How's it going?"

# Remove punctuation
cleaned_str = remove_punctuation(input_str)

# Print the cleaned string
print("Original string:", input_str)
print("Cleaned string:", cleaned_str)

Original string: Hello, world! How's it going?
Cleaned string: Hello world Hows it going


### 38. Check if a string contains only digits.

In [43]:
def contains_only_digits(input_string):
    # Check if all characters in the string are digits
    return input_string.isdigit()

# Example strings
string1 = "12345"
string2 = "Hello123"
string3 = "456.789"

# Check if strings contain only digits
result1 = contains_only_digits(string1)
result2 = contains_only_digits(string2)
result3 = contains_only_digits(string3)

# Print the results
print(f"'{string1}' contains only digits:", result1)
print(f"'{string2}' contains only digits:", result2)
print(f"'{string3}' contains only digits:", result3)

'12345' contains only digits: True
'Hello123' contains only digits: False
'456.789' contains only digits: False


### 39. Check if a string contains only alphabets.

In [44]:
def contains_only_alphabets(input_string):
    # Check if all characters in the string are alphabetic
    return input_string.isalpha()

# Example strings
string1 = "Hello"
string2 = "Hello123"
string3 = "12345"

# Check if strings contain only alphabets
result1 = contains_only_alphabets(string1)
result2 = contains_only_alphabets(string2)
result3 = contains_only_alphabets(string3)

# Print the results
print(f"'{string1}' contains only alphabets:", result1)
print(f"'{string2}' contains only alphabets:", result2)
print(f"'{string3}' contains only alphabets:", result3)

'Hello' contains only alphabets: True
'Hello123' contains only alphabets: False
'12345' contains only alphabets: False


### 40. Convert a string to a list of characters.

In [45]:
def string_to_list(input_string):
    # Use list() constructor to convert the string to a list of characters
    char_list = list(input_string)
    return char_list

# Example string
input_str = "Hello, world!"

# Convert the string to a list of characters
char_list = string_to_list(input_str)

# Print the list of characters
print("Original string:", input_str)
print("List of characters:", char_list)

Original string: Hello, world!
List of characters: ['H', 'e', 'l', 'l', 'o', ',', ' ', 'w', 'o', 'r', 'l', 'd', '!']


### 41. Check if two strings are anagrams.

In [46]:
def are_anagrams(str1, str2):
    # Remove spaces and convert strings to lowercase for accurate comparison
    str1 = str1.replace(" ", "").lower()
    str2 = str2.replace(" ", "").lower()

    # Sort the characters in both strings and compare
    return sorted(str1) == sorted(str2)

# Example strings
string1 = "listen"
string2 = "silent"
string3 = "hello"
string4 = "world"

# Check if strings are anagrams
result1 = are_anagrams(string1, string2)
result2 = are_anagrams(string3, string4)

# Print the results
print(f"'{string1}' and '{string2}' are anagrams:", result1)
print(f"'{string3}' and '{string4}' are anagrams:", result2)

'listen' and 'silent' are anagrams: True
'hello' and 'world' are anagrams: False


### 42. Encode a string using a Caesar cipher.

A Caesar cipher is a simple encryption technique where each letter in the plaintext is shifted a certain number of places down or up the alphabet. Here's a Python code snippet to encode a string using a Caesar cipher:

In [47]:
# Define a function named caesar_cipher that encodes a string using a Caesar cipher.
def caesar_cipher(text, shift):
  """
  Encodes a string using a Caesar cipher.

  Args:
    text: The string to encode.
    shift: The number of positions to shift each letter.

  Returns:
    The encoded string.
  """

  # Initialize an empty string to store the encoded text.
  encoded_text = ""

  # Iterate through each character in the input text.
  for char in text:
    # Check if the character is alphabetic.
    if char.isalpha():
      # Calculate the encoded character's Unicode code point value by shifting it by the specified amount.
      # Ensure the value wraps around within the lowercase alphabet range (a-z).
      encoded_char = chr((ord(char) + shift - ord('a')) % 26 + ord('a'))
    else:
      # Keep non-alphabetic characters unchanged.
      encoded_char = char

    # Add the encoded character to the encoded text.
    encoded_text += encoded_char

  # Return the resulting encoded text.
  return encoded_text

# Define the input text and the shift value for encoding.
text = "Hello, world!"
shift = 3

# Call the caesar_cipher function to encode the text using the specified shift.
encoded_text = caesar_cipher(text, shift)

# Print the encoded text.
print("Encoded text:", encoded_text)

Encoded text: ehoor, zruog!


### 43. Decode a Caesar cipher encoded string.

In [48]:
# Define a function to decode a string using a Caesar cipher
def caesar_cipher_decoder(text, shift):
    """
    Decodes a string using a Caesar cipher.

    Args:
        text: The string to decode.
        shift: The number of positions to shift each letter.

    Returns:
        The decoded string.
    """

    # Initialize an empty string to store the decoded text
    decoded_text = ""

    # Loop through each character in the input text
    for char in text:
        # Check if the character is an alphabetic character
        if char.isalpha():
            # Calculate the decoded character using the shift value
            decoded_char = chr((ord(char) - shift - ord('a')) % 26 + ord('a'))
        else:
            # If the character is not alphabetic, keep it unchanged
            decoded_char = char

        # Add the decoded character to the decoded text
        decoded_text += decoded_char

    # Return the fully decoded text
    return decoded_text

# Example input
text = "lopp, zruog!"
shift = 3

# Call the caesar_cipher_decoder function to decode the input text
decoded_text = caesar_cipher_decoder(text, shift)

# Print the decoded text
print("Decoded text:", decoded_text)

Decoded text: ilmm, world!


### 44. Find the most frequent word in a string.

In [49]:
import re
from collections import Counter

def most_frequent_word(input_string):
    # Remove punctuation and convert to lowercase
    clean_string = re.sub(r'[^\w\s]', '', input_string).lower()

    # Split the string into words
    words = clean_string.split()

    # Use Counter to count word frequencies
    word_counter = Counter(words)

    # Find the most common word
    most_common_word = word_counter.most_common(1)[0][0]




           return most_common_word

# Example string
input_str = "Hello world, hello there! How's the world?"

# Find the most frequent word
most_common = most_frequent_word(input_str)

# Print the result
print("Most frequent word:", most_common)

IndentationError: unexpected indent (56501141.py, line 20)

### 45. Find all unique words in a string.

In [50]:
import re

def unique_words(input_string):
    # Remove punctuation and convert to lowercase
    clean_string = re.sub(r'[^\w\s]', '', input_string).lower()

    # Split the string into words and convert to a set for uniqueness
    words = set(clean_string.split())

    return words

# Example string
input_str = "Hello world, hello there! How's the world?"

# Find unique words
unique_word_set = unique_words(input_str)

# Print the result
print("Unique words:", unique_word_set)

Unique words: {'the', 'there', 'world', 'hows', 'hello'}


### 46. Count the number of syllables in a string.

In [51]:
import re

def count_syllables(word):
    # Count vowel groups using regular expression
    vowel_groups = re.findall(r'[aeiouy]+', word, re.IGNORECASE)

    return len(vowel_groups)

# Example words
word1 = "hello"
word2 = "banana"
word3 = "syllable"

# Count syllables
syllables1 = count_syllables(word1)
syllables2 = count_syllables(word2)
syllables3 = count_syllables(word3)

# Print the results
print(f"'{word1}' has {syllables1} syllables.")
print(f"'{word2}' has {syllables2} syllables.")
print(f"'{word3}' has {syllables3} syllables.")

'hello' has 2 syllables.
'banana' has 3 syllables.
'syllable' has 3 syllables.


### 47. Check if a string contains any special characters.

In [52]:
import re

def contains_special_characters(input_string):
    # Define a regular expression pattern to match special characters
    pattern = re.compile(r'[!@#$%^&*()_+{}\[\]:;<>,.?~\\/]')

    # Use the search() method to find a match
    match = pattern.search(input_string)

    # Return True if a match is found, False otherwise
    return bool(match)

# Example strings
string1 = "Hello, world!"
string2 = "This is a test."
string3 = "Special@Characters"

# Check if strings contain special characters
result1 = contains_special_characters(string1)
result2 = contains_special_characters(string2)
result3 = contains_special_characters(string3)

# Print the results
print(f"'{string1}' contains special characters:", result1)
print(f"'{string2}' contains special characters:", result2)
print(f"'{string3}' contains special characters:", result3)

'Hello, world!' contains special characters: True
'This is a test.' contains special characters: True
'Special@Characters' contains special characters: True


### 48. Remove the nth word from a string.

In [53]:
def remove_nth_word(input_string, n):
    # Split the input string into words
    words = input_string.split()

    # Check if n is within a valid range
    if n >= 1 and n <= len(words):
        # Remove the nth word by excluding it from the words list
        removed_word = words.pop(n - 1)

        # Join the remaining words to form the modified string
        modified_string = ' '.join(words)

        return modified_string, removed_word
    else:
        return None, None

# Example string and n value
input_str = "This is an example sentence to test the function."
n_value = 4

# Remove the nth word
modified_str, removed_word = remove_nth_word(input_str, n_value)

# Print the results
print("Original string:", input_str)
if modified_str is not None:
    print("Modified string:", modified_str)
    print("Removed word:", removed_word)
else:
    print("Invalid n value.")

Original string: This is an example sentence to test the function.
Modified string: This is an sentence to test the function.
Removed word: example


### 49. Insert a word at the nth position in a string.

In [54]:
def insert_word_at_nth_position(string, word, n):
    # Split the string into a list of words
    words = string.split()
    
    # Insert the word at the nth position
    words.insert(n - 1, word)
    
    # Join the words back into a string
    new_string = ' '.join(words)
    
    return new_string

# Example usage:
original_string = "This is a sample string."
word_to_insert = "new"
position_to_insert = 4

result = insert_word_at_nth_position(original_string, word_to_insert, position_to_insert)
print("Original String:", original_string)
print("Word to Insert:", word_to_insert)
print("Position to Insert:", position_to_insert)
print("Result:", result)


Original String: This is a sample string.
Word to Insert: new
Position to Insert: 4
Result: This is a new sample string.


### 50. Convert a CSV string to a list of lists.

In [55]:
def csv_string_to_list(csv_string):
    # Split the CSV string into lines
    lines = csv_string.split('\n')

    # Initialize an empty list to store the result
    result = []

    for line in lines:
        # Split each line into fields using comma as the delimiter
        fields = line.split(',')

        # Append the fields to the result list as a row
        result.append(fields)

    return result

# Example CSV string
csv_data = "Name, Age, Country\nJohn, 25, USA\nAlice, 30, Canada\nBob, 22, UK"

# Convert CSV string to a list of lists
list_of_lists = csv_string_to_list(csv_data)

# Print the result
for row in list_of_lists:
    print(row)

['Name', ' Age', ' Country']
['John', ' 25', ' USA']
['Alice', ' 30', ' Canada']
['Bob', ' 22', ' UK']


## **List based practice problem :**


### 1. Create a list with integers from 1 to 10.

In [56]:
# Use a list comprehension to create a list of integers from 1 to 10
integer_list = [i for i in range(1, 11)]

# Print the list
print(integer_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


- We use a list comprehension, a concise way to create lists in Python, to generate the list of integers from 1 to 10.
- The expression [i for i in range(1, 11)] iterates over the range of numbers from 1 (inclusive) to 11 (exclusive), and for each number i, it adds i to the list.
- The resulting list is stored in the variable integer_list.
- We print the integer_list using the print() statement.

### 2. Find the length of a list without using the `len()` function.

In [57]:
def custom_len(input_list):
    count = 0
    for _ in input_list:
        count += 1
    return count

# Example list
my_list = [10, 20, 30, 40, 50]

# Find the length of the list using the custom_len function
length = custom_len(my_list)

# Print the length of the list
print("Length of the list:", length)

Length of the list: 5


In [58]:
s = "Name, Age, Country\nJohn, 25, USA\nAlice, 30, Canada\nBob, 22, UK"
lines = s.split("\n")

lst = []
for line in lines:
  field = line.split(",")
  lst.append(field)

for row in lst:
  print(row)


['Name', ' Age', ' Country']
['John', ' 25', ' USA']
['Alice', ' 30', ' Canada']
['Bob', ' 22', ' UK']


- We define a function custom_len(input_list) that takes a list as input.
- Inside the function, we initialize a variable count to keep track of the number of elements in the list.
- We use a for loop to iterate through each element in the input list. We use an underscore _ as the loop variable name since we're not using it within the loop.
- Inside the loop, for each element, we increment the count by 1.
After the loop completes, we return the final value of count as the length of the list.
- We provide an example list my_list containing elements.
- We call the custom_len() function to find the length of the list using the custom approach and store the result in the variable length.
- Finally, we print the length of the list using the print() statement.

### 3. Append an element to the end of a list.

In [59]:
# Example list
my_list = [10, 20, 30]

# Element to append
new_element = 40

# Append the new element to the end of the list
my_list.append(new_element)

# Print the updated list
print("Updated list:", my_list)

Updated list: [10, 20, 30, 40]


- We start with an example list my_list containing some elements.
- We have a new element, new_element, that we want to add to the end of the list.
- We use the append() method on the list to add the new_element to the end.
- After the append() operation, the my_list will be updated with the new element at the end.
- We print the updated list using the print() statement.

### 4. Insert an element at a specific index in a list.

In [60]:
# Example list
my_list = [10, 20, 30, 40, 50]

# Element to insert
new_element = 25

# Index at which to insert the element
index_to_insert = 2

# Insert the new element at the specified index
my_list.insert(index_to_insert, new_element)

# Print the updated list
print("Updated list:", my_list)

Updated list: [10, 20, 25, 30, 40, 50]


- We start with an example list my_list containing some elements.
- We have a new element, new_element, that we want to insert into the list.
- We also specify the index at which we want to insert the new element using the index_to_insert variable.
- We use the insert() method on the list to add the new_element at the specified index. The syntax is list.insert(index, element).
- After the insert() operation, the my_list will be updated with the new element inserted at the specified index.
- We print the updated list using the print() statement.

### 5. Remove an element from a list by its value.

In [61]:
# Example list
my_list = [10, 20, 30, 40, 50]

# Element to remove
element_to_remove = 30

# Remove the element by its value
my_list.remove(element_to_remove)

# Print the updated list
print("Updated list:", my_list)

Updated list: [10, 20, 40, 50]


- We start with an example list my_list containing some elements.
- We have an element, element_to_remove, that we want to remove from the list by its value.
- We use the remove() method on the list to remove the element with the specified value. The syntax is list.remove(element).
- After the remove() operation, the my_list will be updated with the specified element removed.
- We print the updated list using the print() statement.

### 6. Remove an element from a list by its index.

In [62]:
# Example list
my_list = [10, 20, 30, 40, 50]

# Index of the element to remove
index_to_remove = 2

# Remove the element at the specified index
removed_element = my_list.pop(index_to_remove)

# Print the updated list and the removed element
print("Updated list:", my_list)
print("Removed element:", removed_element)

Updated list: [10, 20, 40, 50]
Removed element: 30


- We start with an example list my_list containing some elements.
- We specify the index of the element we want to remove using the index_to_remove variable.
- We use the pop() method on the list to remove the element at the specified index. The syntax is list.pop(index). The method also returns the removed element.
- After the pop() operation, the my_list will be updated with the specified element removed.
- We store the removed element in the variable removed_element.
- We print the updated list using the print() statement, along with the removed element.

### 7. Check if an element exists in a list.

In [63]:
# Example list
my_list = [10, 20, 30, 40, 50]

# Element to check
element_to_check = 30

# Check if the element exists in the list
if element_to_check in my_list:
    print(f"{element_to_check} exists in the list.")
else:
    print(f"{element_to_check} does not exist in the list.")

30 exists in the list.


- We start with an example list my_list containing some elements.
- We specify the element we want to check using the element_to_check variable.
- We use the in operator to check if the element_to_check exists in the my_list.
- If the element exists in the list, the condition element_to_check in my_list will be True, and we print that the element exists.
- If the element does not exist in the list, the condition will be False, and we print that the element does not exist.

### 8. Find the index of the first occurrence of an element in a list.

In [64]:
# Example list
my_list = [10, 20, 30, 40, 50, 30]

# Element to find the index of
element_to_find = 30

# Find the index of the first occurrence of the element
index = my_list.index(element_to_find)

# Print the index
print(f"The index of {element_to_find} is {index}")

The index of 30 is 2


- We start with an example list my_list containing some elements.
- We specify the element for which we want to find the index using the element_to_find variable.
- We use the index() method on the list to find the index of the first occurrence of the element_to_find.
- The method returns the index of the first occurrence of the element.
- We print the index using the print() statement.

### 9. Count the occurrences of an element in a list.

In [65]:
# Example list
my_list = [10, 20, 30, 40, 50, 30, 30]

# Element to count occurrences of
element_to_count = 30

# Count the occurrences of the element
count = my_list.count(element_to_count)

# Print the count
print(f"The element {element_to_count} occurs {count} times in the list.")

The element 30 occurs 3 times in the list.


- We start with an example list my_list containing some elements.
- We specify the element for which we want to count occurrences using the element_to_count variable.
- We use the count() method on the list to count the occurrences of the element_to_count.
- The method returns the count of occurrences of the element.
- We print the count using the print() statement.

### 10. Reverse the order of elements in a list.

In [66]:
# Example list
my_list = [10, 20, 30, 40, 50]

# Reverse the order of elements in the list
my_list.reverse()

# Print the reversed list
print("Reversed list:", my_list)

Reversed list: [50, 40, 30, 20, 10]


- We start with an example list my_list containing some elements.
- We use the reverse() method on the list to reverse the order of elements in-place.
- After the reverse() operation, the my_list will be updated with the elements in reverse order.
- We print the reversed list using the print() statement.

### 11. Sort a list in ascending order.

In [67]:
# Example list
my_list = [50, 10, 30, 40, 20]

# Sort the list in ascending order
my_list.sort()

# Print the sorted list
print("Sorted list in ascending order:", my_list)

Sorted list in ascending order: [10, 20, 30, 40, 50]


- We start with an example list my_list containing some elements.
- We use the sort() method on the list to sort the elements in ascending order in-place.
- After the sort() operation, the my_list will be updated with the elements sorted in ascending order.
- We print the sorted list using the print() statement.

### 12. Sort a list in descending order.

In [68]:
# Example list
my_list = [50, 10, 30, 40, 20]

# Sort the list in descending order
my_list.sort(reverse=True)

# Print the sorted list
print("Sorted list in descending order:", my_list)

Sorted list in descending order: [50, 40, 30, 20, 10]


- We start with an example list my_list containing some elements.
- We use the sort() method on the list with the reverse parameter set to True to sort the elements in descending order in-place.
- After the sort() operation, the my_list will be updated with the elements sorted in descending order.
- We print the sorted list using the print() statement.

### 13. Create a list of even numbers from 1 to 20.

In [69]:
# Use a list comprehension to create a list of even numbers from 1 to 20
even_numbers = [x for x in range(2, 21, 2)]

# Print the list of even numbers
print("List of even numbers:", even_numbers)

List of even numbers: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


- We use a list comprehension to generate the list of even numbers.
- The expression [x for x in range(2, 21, 2)] iterates over the range of numbers from 2 to 20 with a step of 2 (to include only even numbers).
- For each even number x in the range, it adds x to the list.
- The resulting list is stored in the variable even_numbers.
- We print the list of even numbers using the print() statement.

### 14. Create a list of odd numbers from 1 to 20.

In [70]:
# Use a list comprehension to create a list of odd numbers from 1 to 20
odd_numbers = [x for x in range(1, 21, 2)]

# Print the list of odd numbers
print("List of odd numbers:", odd_numbers)

List of odd numbers: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


- We use a list comprehension to generate the list of odd numbers.
- The expression [x for x in range(1, 21, 2)] iterates over the range of numbers from 1 to 20 with a step of 2 (to include only odd numbers).
- For each odd number x in the range, it adds x to the list.
- The resulting list is stored in the variable odd_numbers.
- We print the list of odd numbers using the print() statement.

### 15. Find the sum of all elements in a list.

In [71]:
# Example list
my_list = [10, 20, 30, 40, 50]

# Calculate the sum of all elements in the list
total_sum = sum(my_list)

# Print the sum
print("Sum of elements:", total_sum)

Sum of elements: 150


- We start with an example list my_list containing some elements.
- We use the sum() function and provide the my_list as an argument to calculate the sum of all elements in the list.
- The sum() function returns the sum of the elements.
- We print the sum using the print() statement.

### 16. Find the maximum value in a list.

In [72]:
# Example list
my_list = [10, 20, 30, 40, 50]

# Find the maximum value in the list
max_value = max(my_list)

# Print the maximum value
print("Maximum value:", max_value)

Maximum value: 50


- We start with an example list my_list containing some elements.
- We use the max() function and provide the my_list as an argument to find the maximum value in the list.
- The max() function returns the maximum value from the elements in the list.
- We print the maximum value using the print() statement.

### 17. Find the minimum value in a list.

In [73]:
# Example list
my_list = [10, 20, 30, 40, 50]

# Find the minimum value in the list
min_value = min(my_list)

# Print the minimum value
print("Minimum value:", min_value)

Minimum value: 10


- We start with an example list my_list containing some elements.
- We use the min() function and provide the my_list as an argument to find the minimum value in the list.
- The min() function returns the minimum value from the elements in the list.
- We print the minimum value using the print() statement.

### 18. Create a list of squares of numbers from 1 to 10.

In [74]:
# Use a list comprehension to create a list of squares of numbers from 1 to 10
squares = [x ** 2 for x in range(1, 11)]

# Print the list of squares
print("List of squares:", squares)

List of squares: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


- We use a list comprehension to generate the list of squares.
- The expression [x ** 2 for x in range(1, 11)] iterates over the range of numbers from 1 to 10.
- For each number x in the range, it calculates the square x ** 2 and adds it to the list.
- The resulting list is stored in the variable squares.
- We print the list of squares using the print() statement.

### 19. Create a list of random numbers.

In [75]:
import random

# Create a list of random integers between 1 and 100
random_integers = [random.randint(1, 100) for _ in range(10)]

# Print the list of random integers
print("List of random integers:", random_integers)

List of random integers: [53, 64, 62, 6, 99, 100, 74, 39, 73, 53]


- Import the random module at the beginning of the code.
- Use a list comprehension to generate the list of random numbers.
- In the first example, the expression [random.random() for _ in range(10)] generates a list of 10 random floating-point numbers between 0 and 1.
- In the second example, the expression [random.randint(1, 100) for _ in range(10)] generates a list of 10 random integers between 1 and 100.
- The resulting list of random numbers (either floating-point numbers or integers) is stored in the appropriate variable (random_numbers or random_integers).
- Print the list of random numbers using the print() statement.

### 20. Remove duplicates from a list.

In [76]:
# Example list with duplicates
my_list = [10, 20, 30, 20, 40, 10, 50, 30]

# Remove duplicates by converting to a set and back to a list
unique_list = list(set(my_list))

# Print the list without duplicates
print("List without duplicates:", unique_list)

List without duplicates: [40, 10, 50, 20, 30]


- We start with an example list my_list containing duplicate elements.
- We convert the list to a set using the set() constructor. Sets automatically remove duplicate elements.
- Then, we convert the set back to a list using the list() constructor, resulting in a list without duplicates.
- The resulting list without duplicates is stored in the variable unique_list.
- We print the list without duplicates using the print() statement.

### 21. Find the common elements between two lists.

In [77]:
21. Find the common elements between two lists.

SyntaxError: invalid syntax (1758263510.py, line 1)

- We start with two example lists, list1 and list2, which contain some elements.
- We use a list comprehension to iterate through each element in list1.
- For each element, we check if it exists in list2 using the element in list2 expression.
- If the element is found in both lists, it is added to the common_elements list.
- The resulting list of common elements is stored in the variable common_elements.
- We print the common elements using the print() statement.

### 22. Find the difference between two lists.

In [78]:
# Example lists
list1 = [10, 20, 30, 40, 50]
list2 = [30, 40, 50, 60, 70]

# Find the difference between lists using the difference() method
difference = list(set(list1).difference(list2))

# Print the difference
print("Difference between lists:", difference)

Difference between lists: [20, 10]


- We start with two example lists, list1 and list2, which contain some elements.
- We use the difference() method on the set created from list1 to find the elements that are not present in list2.
- The difference() method returns a set containing the elements that are in list1 but not in list2.
- We convert the resulting set back to a list using the list() constructor to get the difference.
- The resulting list of the difference is stored in the variable difference.
- We print the difference using the print() statement.

### 23. Merge two lists.

In [79]:
# Example lists
list1 = [10, 20, 30]
list2 = [40, 50, 60]

# Merge lists using the + operator
merged_list = list1 + list2

# Print the merged list
print("Merged list:", merged_list)

Merged list: [10, 20, 30, 40, 50, 60]


- We start with two example lists, list1 and list2, which contain some elements.
- We use the + operator to concatenate list1 and list2, creating a new list merged_list.
- The + operator combines the elements of both lists into a single list.
- The resulting merged list is stored in the variable merged_list.
- We print the merged list using the print() statement.

### 24. Multiply all elements in a list by 2.

In [80]:
# Example list
my_list = [10, 20, 30, 40, 50]

# Multiply all elements by 2 using a list comprehension
multiplied_list = [x * 2 for x in my_list]

# Print the multiplied list
print("Multiplied list:", multiplied_list)

Multiplied list: [20, 40, 60, 80, 100]


- We start with an example list my_list containing some elements.
- We use a list comprehension to iterate through each element in my_list.
- For each element, we multiply it by 2 (x * 2) and add the result to the multiplied_list.
- The resulting list with multiplied elements is stored in the variable multiplied_list.
- We print the multiplied list using the print() statement.

### 25. Filter out all even numbers from a list.

- We start with an example list my_list containing some elements.
- We use a list comprehension to iterate through each element in my_list.
- For each element, we use a conditional statement (x % 2 != 0) to check if the element is not even (odd).
  - If the element is odd (not even), it is added to the filtered_list.
  - The resulting list with odd numbers is stored in the variable filtered_list.
- We print the filtered list using the print() statement.

### 26. Convert a list of strings to a list of integers.

In [81]:
# Example list of strings
string_list = ["10", "20", "30", "40", "50"]

# Convert list of strings to list of integers using a list comprehension
integer_list = [int(x) for x in string_list]

# Print the list of integers
print("List of integers:", integer_list)

List of integers: [10, 20, 30, 40, 50]


- We start with an example list string_list containing strings representing numbers.
- We use a list comprehension to iterate through each string in string_list.
- For each string, we use the int() function to convert it to an integer and add the integer to the integer_list.
- The resulting list of integers is stored in the variable integer_list.
- We print the list of integers using the print() statement.

### 27. Convert a list of integers to a list of strings.

In [82]:
# Example list of integers
integer_list = [10, 20, 30, 40, 50]

# Convert list of integers to list of strings using a list comprehension
string_list = [str(x) for x in integer_list]

# Print the list of strings
print("List of strings:", string_list)

List of strings: ['10', '20', '30', '40', '50']


- We start with an example list integer_list containing integers.
- We use a list comprehension to iterate through each integer in integer_list.
- For each integer, we use the str() function to convert it to a string and add the string to the string_list.
- The resulting list of strings is stored in the variable string_list.
- We print the list of strings using the print() statement.

### 28. Flatten a nested list.

In [83]:
# Example nested list
nested_list = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

# Function to flatten a nested list
def flatten_list(nested):
    flattened = []
    for sublist in nested:
        if isinstance(sublist, list):
            flattened.extend(flatten_list(sublist))
        else:
            flattened.append(sublist)
    return flattened

# Flatten the nested list
flattened_list = flatten_list(nested_list)

# Print the flattened list
print("Flattened list:", flattened_list)

Flattened list: [1, 2, 3, 4, 5, 6, 7, 8, 9]


- We start with an example nested list nested_list containing sublists.
- We define a function flatten_list() that takes a nested list as an argument.
- Inside the function, we initialize an empty list called flattened to store the flattened elements.
- We iterate through each element in the nested list.
- If an element is a sublist (i.e., it's an instance of the list type), we recursively call the flatten_list() function on that sublist and extend the flattened list with its flattened contents.
- If an element is not a sublist, we directly append it to the flattened list.
- After processing all elements, the function returns the flattened list.
We call the flatten_list() function on the nested_list to get the flattened list.
- We print the flattened list using the print() statement.

### 29. Create a list of the first 10 Fibonacci numbers.

In [84]:
# Function to generate the first n Fibonacci numbers
def generate_fibonacci(n):
    fibonacci_list = [0, 1]  # Initialize the list with the first two Fibonacci numbers

    for i in range(2, n):
        next_fibonacci = fibonacci_list[i - 1] + fibonacci_list[i - 2]
        fibonacci_list.append(next_fibonacci)

    return fibonacci_list

# Generate the first 10 Fibonacci numbers
fibonacci_numbers = generate_fibonacci(2)

# Print the list of Fibonacci numbers
print("First 10 Fibonacci numbers:", fibonacci_numbers)

First 10 Fibonacci numbers: [0, 1]


- We define a function generate_fibonacci() that takes the parameter n to determine how many Fibonacci numbers to generate.
- Inside the function, we initialize a list called fibonacci_list with the first two Fibonacci numbers: 0 and 1.
- We use a loop that starts from the third Fibonacci number (index 2) up to the desired count n.
- In each iteration, we calculate the next Fibonacci number by adding the last two numbers in the fibonacci_list.
- We append the next Fibonacci number to the fibonacci_list.
- After generating all Fibonacci numbers, the function returns the fibonacci_list.
- We call the generate_fibonacci() function with the argument 10 to generate the first 10 Fibonacci numbers.
- We print the list of Fibonacci numbers using the print() statement.

### 30. Check if a list is sorted.
  
  - Checking for ascending order:

In [85]:
# Function to check if a list is sorted in ascending order
def is_sorted_ascending(lst):
    for i in range(1, len(lst)):
        if lst[i] < lst[i - 1]:
            return False
    return True

# Example list
ascending_list = [10, 20, 30, 40, 50]

# Check if the list is sorted in ascending order
if is_sorted_ascending(ascending_list):
    print("The list is sorted in ascending order.")
else:
    print("The list is not sorted in ascending order.")

The list is sorted in ascending order.


- We define a function is_sorted_ascending() that takes a list lst as an argument.
- Inside the function, we iterate through the list starting from the second element (i = 1) up to the last element.
- In each iteration, we compare the current element with the previous element (lst[i] < lst[i - 1]). If it's smaller, it indicates the list is not sorted in ascending order.
- If the loop completes without finding any out-of-order elements, the function returns True, indicating that the list is sorted in ascending order.

### 31. Rotate a list to the left by `n` positions.

In [86]:
# Function to rotate a list to the left by n positions
def rotate_left(lst, n):
    n = n % len(lst)  # Normalize n to handle cases where n is larger than the list length
    # print(n)
    rotated = lst[n:] + lst[:n]
    return rotated

# Example list
my_list = [1, 2, 3, 4, 5, 6]

# Number of positions to rotate by
n = 2

# Rotate the list to the left by n positions
rotated_list = rotate_left(my_list, n)

# Print the rotated list
print("Rotated list:", rotated_list)

Rotated list: [3, 4, 5, 6, 1, 2]


- We define a function rotate_left() that takes a list lst and the number of positions n as arguments.
- Inside the function, we normalize n by taking the modulo of n with the length of the list. This handles cases where n is larger than the list length.
- We use list slicing to create the rotated list. We take elements from position n to the end (lst[n:]) and concatenate it with elements from the beginning to position n (lst[:n]).
- The resulting rotated list represents the original list rotated to the left by n positions.
- We return the rotated list from the function.
- In the example code, we have an example list my_list and specify the number of positions n to rotate by.
- We call the rotate_left() function to get the rotated list.
- We print the rotated list using the print() statement.

### 32. Rotate a list to the right by `n` positions.

In [87]:
# Function to rotate a list to the right by n positions
def rotate_right(lst, n):
    n = n % len(lst)  # Normalize n to handle cases where n is larger than the list length
    # print(n)
    rotated = lst[-n:] + lst[:-n]
    return rotated

# Example list
my_list = [1, 2, 3, 4, 5, 6]

# Number of positions to rotate by
n = 2

# Rotate the list to the right by n positions
rotated_list = rotate_right(my_list, n)

# Print the rotated list
print("Rotated list:", rotated_list)

Rotated list: [5, 6, 1, 2, 3, 4]


- We define a function rotate_right() that takes a list lst and the number of positions n as arguments.
- Inside the function, we normalize n by taking the modulo of n with the length of the list. This handles cases where n is larger than the list length.
- We use list slicing to create the rotated list. We take elements from the last n positions to the end (lst[-n:]) and concatenate it with elements from the beginning to the position n from the end (lst[:-n]).
- The resulting rotated list represents the original list rotated to the right by n positions.
- We return the rotated list from the function.
- In the example code, we have an example list my_list and specify the number of positions n to rotate by.
- We call the rotate_right() function to get the rotated list.
- We print the rotated list using the print() statement.

### 33. Create a list of prime numbers up to 50.

In [88]:
# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
      print(i,num)
      if num % i == 0 or num % (i + 2) == 0:
          return False
      i += 6
    return True

# Create a list of prime numbers up to 50
prime_numbers = [num for num in range(2,30) if is_prime(num)]

# Print the list of prime numbers
print("List of prime numbers up to 50:", prime_numbers)

5 25
5 29
List of prime numbers up to 50: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


- We define a function is_prime() that takes a number num as an argument and returns True if the number is prime and False otherwise. The function uses a primality testing algorithm based on the fact that prime numbers greater than 3 can be written in the form 6k ± 1.
- Inside the function, we handle some base cases (numbers less than or equal to 3), and then we use a loop to check divisibility by numbers in the form of 6k ± 1.
- We define a list comprehension to generate the list of prime numbers. The comprehension iterates through the numbers from 2 to 50 and includes the number in the list if it is prime according to the is_prime() function.
- The resulting list of prime numbers is stored in the variable prime_numbers.
- We print the list of prime numbers using the print() statement.

### 34. Split a list into chunks of size `n`.

In [89]:
# Create a list of prime numbers up to 50 using Sieve of Eratosthenes algorithm
def sieve_of_eratosthenes(limit):
    primes = []
    is_prime = [True] * (limit + 1)
    is_prime[0] = is_prime[1] = False

    for num in range(2, int(limit ** 0.5) + 1):
        if is_prime[num]:
            primes.append(num)
            for multiple in range(num * num, limit + 1, num):
                is_prime[multiple] = False

    for num in range(int(limit ** 0.5) + 1, limit + 1):
        if is_prime[num]:
            primes.append(num)

    return primes

# Create a list of prime numbers up to 50
prime_numbers = sieve_of_eratosthenes(50)

# Print the list of prime numbers
print("List of prime numbers up to 50:", prime_numbers)

List of prime numbers up to 50: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


- We define a function sieve_of_eratosthenes() that takes a limit as an argument and returns a list of prime numbers up to the limit.
- Inside the function, we initialize two lists: primes to store the prime numbers and is_prime as a boolean list to mark whether a number is prime or not.
- We iterate through the numbers from 2 to the square root of the limit. For each number, if it's marked as prime (is_prime[num] is True), we add it to the primes list and mark its multiples as not prime.
- After the first loop, we iterate through the remaining numbers from the square root of the limit to the limit. If a number is marked as prime, we add it to the primes list.
- We call the sieve_of_eratosthenes() function with the argument 50 to generate the list of prime numbers up to 50.
- We print the list of prime numbers using the print() statement.

### 35. Find the second largest number in a list.

In [90]:
# Example list
my_list = [10, 5, 20, 15, 30, 25]

# Remove duplicates and sort the list in ascending order
sorted_list = sorted(set(my_list))

# Find the second largest number
if len(sorted_list) >= 2:
    second_largest = sorted_list[-2]
    print("Second largest number:", second_largest)
else:
    print("The list does not contain enough elements.")

Second largest number: 25


- We start with an example list my_list containing numbers.
- We remove duplicates from the list using the set() function.
- We sort the list in ascending order using the sorted() function.
- We check if the sorted list has at least two elements. If it does, we access the second-to-last element using negative indexing (sorted_list[-2]) to get the second largest number.
- If the list has fewer than two elements, we print a message indicating that the list does not contain enough elements to find the second largest.
- We print the second largest number using the print() statement.

### 36. Replace every element in a list with its square.

In [91]:
# Example list
my_list = [2, 4, 6, 8, 10]

# Replace every element with its square using a list comprehension
squared_list = [x ** 2 for x in my_list]

# Print the squared list
print("Squared list:", squared_list)

Squared list: [4, 16, 36, 64, 100]


- We start with an example list my_list containing numbers.
- We use a list comprehension to iterate through each element in my_list.
- For each element, we calculate its square (x ** 2) and add the squared value to the squared_list.
- The resulting list with squared values is stored in the variable squared_list.
- We print the squared list using the print() statement.

### 37. Convert a list to a dictionary where list elements become keys and their indices become values.

In [92]:
# Example list
my_list = ['apple', 'banana', 'cherry', 'date', 'elderberry']

# Convert list to dictionary using dictionary comprehension
my_dict = {element: index for index, element in enumerate(my_list)}

# Print the resulting dictionary
print("Converted dictionary:", my_dict)

Converted dictionary: {'apple': 0, 'banana': 1, 'cherry': 2, 'date': 3, 'elderberry': 4}


- We start with an example list my_list containing elements.
- We use a dictionary comprehension to iterate through each element and its corresponding index in the list.
- For each element and index pair, we create a key-value pair in the dictionary, where the element becomes the key and the index becomes the value.
- The resulting dictionary is stored in the variable my_dict.
- We print the converted dictionary using the print() statement.

### 38. Shuffle the elements of a list randomly.

In [93]:
import random

# Example list
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Shuffle the list randomly
random.shuffle(my_list)

# Print the shuffled list
print("Shuffled list:", my_list)

Shuffled list: [3, 5, 7, 2, 8, 10, 6, 4, 9, 1]


- Import the random module to access the shuffle() function.
- We start with an example list my_list containing elements.
- We use the random.shuffle() function to shuffle the elements of the list randomly.
- The original order of the list is modified, and the elements are rearranged randomly.
- We print the shuffled list using the print() statement.

### 39. Create a list of the first 10 factorial numbers.

In [94]:
# Function to calculate factorial
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

# Create a list of the first 10 factorial numbers
factorial_numbers = [factorial(i) for i in range(10)]

# Print the list of factorial numbers
print("List of the first 10 factorial numbers:", factorial_numbers)

List of the first 10 factorial numbers: [1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880]


- We define a function factorial() that takes an integer n as an argument and calculates the factorial of n using recursion.
- Inside the function, we handle base cases where n is 0 or 1, and in other cases, we calculate n times the factorial of n-1.
- We use a list comprehension to generate the list of the first 10 factorial numbers. We iterate through the range of numbers from 0 to 9 and calculate the factorial for each number.
- The resulting list of factorial numbers is stored in the variable factorial_numbers.
- We print the list of factorial numbers using the print() statement.

### 40. Check if two lists have at least one element in common.

In [95]:
# Function to check if two lists have at least one element in common
def has_common_element(list1, list2):
    for item in list1:
        if item in list2:
            return True
    return False

# Example lists
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]

# Check if the two lists have at least one element in common
if has_common_element(list1, list2):
    print("The lists have at least one common element.")
else:
    print("The lists do not have any common elements.")

The lists have at least one common element.


- We define a function has_common_element() that takes two lists list1 and list2 as arguments.
- Inside the function, we use a loop to iterate through each element in list1.
- For each element, we check if it is present in list2 using the in operator.
- If we find at least one element that is present in both lists, we return True.
- If the loop completes without finding any common element, we return False.
- In the example code, we have two example lists list1 and list2.
- We call the has_common_element() function with the two lists to check if they have at least one element in common.
- We print the appropriate message using the print() statement.

### 41. Remove all elements from a list.

In [96]:
# Example list
my_list = [1, 2, 3, 4, 5]

# Clear all elements from the list
my_list.clear()

# Print the empty list
print("Empty list:", my_list)

Empty list: []


Using the clear() method, approach will result in an empty list.

### 42. Replace negative numbers in a list with 0.

In [97]:
# Example list
my_list = [10, -5, 20, -15, 30, -25]

# Step 1: Iterate through the list and replace negative numbers with 0
for i in range(len(my_list)):
    if my_list[i] < 0:
        my_list[i] = 0

# Print the list after replacing negative numbers with 0
print("List after replacing negative numbers with 0:", my_list)

List after replacing negative numbers with 0: [10, 0, 20, 0, 30, 0]


- We start with an example list my_list containing both positive and negative numbers.
- We use a for loop to iterate through the indices of the list using the range() function.
- Inside the loop, we check if the element at index i is less than 0 (negative).
- If it is negative, we replace the element at index i with 0.
- After iterating through all elements, the list will have negative numbers replaced with 0.
- We print the modified list using the print() statement.

### 43. Convert a string into a list of words.

In [98]:
# Example string
my_string = "Hello, this is a sample sentence."

# Convert the string into a list of words
word_list = my_string.split()

# Print the list of words
print("List of words:", word_list)

List of words: ['Hello,', 'this', 'is', 'a', 'sample', 'sentence.']


- We start with an example string my_string containing a sentence.
- We use the split() method on the string. By default, the split() method splits the string into words based on whitespace characters (spaces, tabs, newlines, etc.).
- The result of the split() method is a list of words, which we store in the variable word_list.
- We print the list of words using the print() statement.

### 44. Convert a list of words into a string.

In [99]:
# Example list of words
word_list = ["Hello,", "this", "is", "a", "sample", "sentence."]

# Convert the list of words into a string
my_string = " ".join(word_list)

# Print the resulting string
print("Converted string:", my_string)

Converted string: Hello, this is a sample sentence.


- We start with an example list word_list containing individual words.
- We use the join() method on a string (in this case, a space " ") to join the words in the list into a single string.
- The join() method takes the list of words as its argument and returns a string where the words are joined by the specified separator (in this case, a space).
- The resulting string is stored in the variable my_string.
- We print the converted string using the print() statement.

### 45. Create a list of the first `n` powers of 2.

In [100]:
# Specify the value of n
n = 5

# Create a list of the first n powers of 2 using a loop
power_list = [2 ** i for i in range(n)]

# Print the list of powers of 2
print("List of the first", n, "powers of 2:", power_list)

List of the first 5 powers of 2: [1, 2, 4, 8, 16]


- We specify the value of n, which indicates the number of powers of 2 to generate.
- We use a list comprehension to calculate the powers of 2 for each value of i from 0 to n-1.
- In each iteration of the loop, we calculate the value 2 ** i to get the powers of 2.
- The resulting list of powers of 2 is stored in the variable power_list.
- We print the list of powers of 2 using the print() statement.

### 46. Find the longest string in a list of strings.

In [101]:
# Example list of strings
string_list = ["apple", "banana", "cherry", "date", "elderberry"]

# Find the longest string in the list
longest_string = ""
for s in string_list:
    if len(s) > len(longest_string):
        longest_string = s

# Print the longest string
print("Longest string:", longest_string)

Longest string: elderberry


- We start with an example list string_list containing strings of different lengths.
- We initialize the variable longest_string with an empty string. This variable will store the longest string found in the list.
- We use a for loop to iterate through each string s in the list.
- Inside the loop, we compare the length of the current string s with the length of the longest_string. If the length of s is greater, we update longest_string to be the current string s.
- After iterating through all strings in the list, the variable longest_string will contain the longest string.
- We print the longest string using the print() statement.

### 47. Find the shortest string in a list of strings.

In [102]:
# Example list of strings
string_list = ["apple", "banana", "cherry", "date", "elderberry"]

# Find the shortest string in the list
shortest_string = string_list[0]  # Initialize with the first string
for s in string_list:
    if len(s) < len(shortest_string):
        shortest_string = s

# Print the shortest string
print("Shortest string:", shortest_string)

Shortest string: date


- We start with an example list string_list containing strings of different lengths.
- We initialize the variable shortest_string with the first string in the list. - This variable will store the shortest string found in the list.
- We use a for loop to iterate through each string s in the list.
- Inside the loop, we compare the length of the current string s with the length of the shortest_string. If the length of s is smaller, we update shortest_string to be the current string s.
- After iterating through all strings in the list, the variable shortest_string will contain the shortest string.
- We print the shortest string using the print() statement.

### 48. Create a list of the first `n` triangular numbers.

In [103]:
# Function to calculate triangular numbers
def triangular_numbers(n):
    return [i * (i + 1) // 2 for i in range(1, n + 1)]

# Specify the value of n
n = 5

# Create a list of the first n triangular numbers
triangular_list = triangular_numbers(n)

# Print the list of triangular numbers
print("List of the first", n, "triangular numbers:", triangular_list)

List of the first 5 triangular numbers: [1, 3, 6, 10, 15]


- We define a function triangular_numbers() that takes an integer n as an argument.
- Inside the function, we use a list comprehension to calculate the triangular numbers for each value of i from 1 to n.
- The formula to calculate the nth triangular number is n * (n + 1) // 2.
- We specify the value of n, which indicates the number of triangular numbers to generate.
- We call the triangular_numbers() function with the value of n to create the list of triangular numbers.
- We print the list of triangular numbers using the print() statement.

### 49. Check if a list contains another list as a subsequence.

In [104]:
# Function to check if a list contains another list as a subsequence
def is_subsequence(subsequence, main_list):
    subseq_index = 0  # Index for the subsequence elements
    for element in main_list:
        if element == subsequence[subseq_index]:
            subseq_index += 1
            if subseq_index == len(subsequence):
                return True
    return False

# Example main list and subsequence
main_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
subsequence = [3, 5, 8]

# Check if the main list contains the subsequence
if is_subsequence(subsequence, main_list):
    print("Main list contains the subsequence.")
else:
    print("Main list does not contain the subsequence.")

Main list contains the subsequence.


- We define a function is_subsequence() that takes two lists as arguments: subsequence (the list to check for as a subsequence) and main_list (the list to search for the subsequence in).
- Inside the function, we use an index subseq_index to keep track of the matching elements in the subsequence.
- We iterate through the elements of the main_list.
- For each element in main_list, we compare it with the current element in the subsequence.
  - If the elements match, we increment the subseq_index to check the next element in the subsequence.
  - If the subseq_index reaches the length of the subsequence, it means the subsequence has been completely matched, and we return True.
  - If we finish iterating through the main_list without completely matching the subsequence, we return False.
- In the example code, we have an example main_list and subsequence.
- We call the is_subsequence() function to check if the main list contains the subsequence.
- We print the result using the print() statement.

### 50. Swap two elements in a list by their indices.

In [105]:
# Example list
my_list = [1, 2, 3, 4, 5]

# Indices of elements to swap
index1 = 1
index2 = 3

# Swap the elements at the specified indices
temp = my_list[index1]
my_list[index1] = my_list[index2]
my_list[index2] = temp

# Print the list after swapping
print("List after swapping elements:", my_list)

List after swapping elements: [1, 4, 3, 2, 5]


- We start with an example list my_list containing elements.
- We specify the indices index1 and index2 of the elements to swap.
- We use a temporary variable temp to hold the value of the element at index1.
- We assign the value of the element at index2 to the element at index1.
- We assign the value of the temporary variable temp (which holds the original value of the element at index1) to the element at index2, effectively swapping the values.
- After the swap, the elements at the specified indices have been swapped.
- We print the list after swapping using the print() statement.

## **Tuple based practice problem :**

---


### 1. Create a tuple with integers from 1 to 5.

In [106]:
# Step 1: Create a tuple
my_tuple = (10, 20, 30, 40, 50)

# Step 2: Access the third element of the tuple
third_element = my_tuple[2]

# Explanation: In this line, we use indexing to access the third element of the tuple.
# Since indexing is 0-based, the third element is at index 2.

# Step 3: Print the third element
print("The third element of the tuple is:", third_element)

The third element of the tuple is: 30


- We use parentheses to create a tuple named my_tuple containing the integers from 1 to 5.
- We print the tuple using the print() statement.

### 2. Access the third element of a tuple.

In [107]:
# Step 1: Create a tuple with some elements
my_tuple = (10, 20, 30, 40, 50)

# Step 2: Access the third element (index 2) of the tuple
third_element = my_tuple[2]

# Step 3: Print the third element
print("The third element of the tuple is:", third_element)

The third element of the tuple is: 30


- We start by creating a tuple named my_tuple with five elements: 10, 20, 30, 40, and 50.
- To access elements of a tuple, we use square brackets [] with the index of the element we want to access. Tuples are zero-indexed, so the third element has an index of 2.
- We store the value of the third element (30) in the variable third_element.
- Finally, we use the print function to display a message along with the value of the third element of the tuple.

### 3. Find the length of a tuple without using the `len()` function.

In [108]:
# Step 1: Create a tuple
my_tuple = (10, 20, 30, 40, 50)

# Step 2: Initialize a variable to count the elements
count = 0

# Step 3: Iterate through the tuple and increment the count for each element
for _ in my_tuple:
    count += 1

# Step 4: Print the length of the tuple
print("The length of the tuple is:", count)

The length of the tuple is: 5


- We start by creating a tuple named my_tuple with five elements.
- We initialize a variable named count to keep track of the number of elements in the tuple. This variable starts with a value of 0.
- We use a for loop to iterate through each element in the tuple. The _ symbol is commonly used as a placeholder for variables when we don't intend to use the variable value.
- Inside the loop, we increment the count variable by 1 for each element in the tuple.
- After the loop completes, we use the print function to display a message along with the value of the count variable, which represents the length of the tuple.

### 4. Count the occurrences of an element in a tuple.

In [109]:
# Step 1: Create a tuple
my_tuple = (10, 20, 30, 20, 40, 50, 20)

# Step 2: Choose the element to count occurrences of
element_to_count = 20

# Step 3: Initialize a variable to keep track of the count
count = 0

# Step 4: Iterate through the tuple and count occurrences of the chosen element
for item in my_tuple:
    if item == element_to_count:
        count += 1

# Step 5: Print the count of occurrences
print(f"The element {element_to_count} appears {count} times in the tuple.")

The element 20 appears 3 times in the tuple.


- We start by creating a tuple named my_tuple with several elements, including multiple occurrences of the element we want to count.
- We choose the element to count occurrences of. In this example, we'll count occurrences of the element 20.
- We initialize a variable named count to keep track of the number of occurrences of the chosen element. This variable starts with a value of 0.
- We use a for loop to iterate through each element in the tuple.
- Inside the loop, we use an if statement to check if the current element item is equal to the element we want to count (element_to_count). If they are equal, we increment the count variable by 1.
- After the loop completes, we use the print function to display a message along with the value of the count variable, indicating how many times the chosen element appears in the tuple.

### 5. Find the index of the first occurrence of an element in a tuple.

In [110]:
# Step 1: Create a tuple
my_tuple = (10, 20, 30, 20, 40, 50)

# Step 2: Choose the element to find the index of
element_to_find = 20

# Step 3: Initialize a variable to keep track of the index
index = -1  # Initialize with -1 to indicate that the element was not found

# Step 4: Iterate through the tuple and find the index of the chosen element
for i, item in enumerate(my_tuple):
    if item == element_to_find:
        index = i
        break  # Exit the loop once the first occurrence is found

# Step 5: Print the index of the first occurrence
if index != -1:
    print(f"The first occurrence of {element_to_find} is at index {index}.")
else:
    print(f"{element_to_find} is not found in the tuple.")

The first occurrence of 20 is at index 1.


- We start by creating a tuple named my_tuple with several elements, including the element for which we want to find the first occurrence.
- We choose the element for which we want to find the index. In this example, we'll find the index of the element 20.
- We initialize a variable named index with a value of -1. This value indicates that the element was not found in the tuple initially.
- We use a for loop along with the enumerate function to iterate through the tuple. The enumerate function provides both the index i and the element item in each iteration.
- Inside the loop, we use an if statement to check if the current element item is equal to the element we want to find (element_to_find). If they are equal, we update the index variable with the value of the current index i and then exit the loop using the break statement.
- After the loop completes, we check if the index value has changed from its initial value of -1. If it has, we print the index of the first occurrence of the element. If not, we print a message indicating that the element was not found in the tuple.

### 6. Check if an element exists in a tuple.

In [111]:
# Step 1: Create a tuple
my_tuple = (10, 20, 30, 40, 50)

# Step 2: Choose the element to check for existence
element_to_check = 30

# Step 3: Check if the element exists in the tuple using the 'in' operator
if element_to_check in my_tuple:
    print(f"{element_to_check} exists in the tuple.")
else:
    print(f"{element_to_check} does not exist in the tuple.")

30 exists in the tuple.


- We start by creating a tuple named my_tuple with several elements.
- We choose the element we want to check for existence. In this example, we're checking for the element 30.
- We use the in operator to directly check if the chosen element exists in the tuple. If it does, we print a message indicating its existence. If not, we print a message indicating its absence.

### 7. Convert a tuple to a list.

In [112]:
# Step 1: Create a tuple
my_tuple = (10, 20, 30, 40, 50)

# Step 2: Convert the tuple to a list
my_list = list(my_tuple)

# Step 3: Print the resulting list
print("Tuple:", my_tuple)
print("List:", my_list)

Tuple: (10, 20, 30, 40, 50)
List: [10, 20, 30, 40, 50]


- We start by creating a tuple named my_tuple with some elements.
- We use the list() function and pass the tuple my_tuple as an argument. This function converts the tuple into a list.
- We print both the original tuple and the converted list to see the transformation.

### 8. Convert a list to a tuple.

In [113]:
# Step 1: Create a list
my_list = [10, 20, 30, 40, 50]

# Step 2: Convert the list to a tuple
my_tuple = tuple(my_list)

# Step 3: Print the resulting tuple
print("List:", my_list)
print("Tuple:", my_tuple)


List: [10, 20, 30, 40, 50]
Tuple: (10, 20, 30, 40, 50)


- We start by creating a list named my_list with some elements.
- We use the tuple() function and pass the list my_list as an argument. This function converts the list into a tuple.
- We print both the original list and the converted tuple to see the transformation.

### 9. Unpack the elements of a tuple into variables.

In [114]:
# Step 1: Create a tuple
my_tuple = (10, 20, 30)

# Step 2: Unpack the elements of the tuple into variables
var1, var2, var3 = my_tuple

# Step 3: Print the variables
print("var1:", var1)
print("var2:", var2)
print("var3:", var3)

var1: 10
var2: 20
var3: 30


- We start by creating a tuple named my_tuple with three elements.
- We use the unpacking assignment to assign the values of the tuple elements to individual variables var1, var2, and var3.
- We print the values of these variables.

### 10. Create a tuple of even numbers from 1 to 10.

In [115]:
# Step 1: Create a list of even numbers using a list comprehension
even_numbers_list = [num for num in range(2, 11, 2)]  # Start from 2, step by 2, end at 10

# Step 2: Convert the list to a tuple
even_numbers_tuple = tuple(even_numbers_list)

# Step 3: Print the resulting tuple
print("Tuple of even numbers:", even_numbers_tuple)

Tuple of even numbers: (2, 4, 6, 8, 10)


- We use a list comprehension to generate a list of even numbers. The range(2, 11, 2) generates numbers starting from 2 and increasing by 2 up to (but not including) 11, giving us the even numbers from 2 to 10.
- We convert the list of even numbers to a tuple using the tuple() function.
- We print the resulting tuple containing the even numbers.

### 11. Create a tuple of odd numbers from 1 to 10.

In [116]:
# Step 1: Create a list of even numbers using a list comprehension
even_numbers_list = [num for num in range(2, 11, 2)]  # Start from 2, step by 2, end at 10

# Step 2: Convert the list to a tuple
even_numbers_tuple = tuple(even_numbers_list)

# Step 3: Print the resulting tuple
print("Tuple of even numbers:", even_numbers_tuple)

Tuple of even numbers: (2, 4, 6, 8, 10)


- We use a list comprehension to generate a list of even numbers. The range(2, 11, 2) generates numbers starting from 2 and increasing by 2 up to (but not including) 11, giving us the even numbers from 2 to 10.
- We convert the list of even numbers to a tuple using the tuple() function.
- We print the resulting tuple containing the even numbers.

### 12. Concatenate two tuples.

In [117]:
# Step 1: Create two tuples
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

# Step 2: Concatenate the two tuples
concatenated_tuple = tuple1 + tuple2

# Step 3: Print the concatenated tuple
print("Concatenated tuple:", concatenated_tuple)

Concatenated tuple: (1, 2, 3, 4, 5, 6)


- We start by creating two tuples named tuple1 and tuple2.
- We use the + operator to concatenate the two tuples, resulting in a new tuple named concatenated_tuple.
- We print the concatenated tuple.

### 13. Repeat a tuple three times.

In [118]:
# Step 1: Create a tuple
original_tuple = (1, 2, 3)

# Step 2: Repeat the tuple three times
repeated_tuple = original_tuple * 3

# Step 3: Print the repeated tuple
print("Repeated tuple:", repeated_tuple)

Repeated tuple: (1, 2, 3, 1, 2, 3, 1, 2, 3)


- We start by creating a tuple named original_tuple with some elements.
- We use the * operator to repeat the tuple three times, resulting in a new tuple named repeated_tuple.
- We print the repeated tuple.

### 14. Check if a tuple is empty.

In [119]:
# Step 1: Create an empty tuple and a non-empty tuple
empty_tuple = ()
non_empty_tuple = (1, 2, 3)

# Step 2: Check if the tuples are empty
if not empty_tuple:
    print("The empty_tuple is empty.")
else:
    print("The empty_tuple is not empty.")

if not non_empty_tuple:
    print("The non_empty_tuple is empty.")
else:
    print("The non_empty_tuple is not empty.")

The empty_tuple is empty.
The non_empty_tuple is not empty.


- We create an empty tuple named empty_tuple and a non-empty tuple named non_empty_tuple for demonstration purposes.
- We use if not empty_tuple to check if the empty_tuple is empty. Since an empty tuple evaluates to False, the first print statement will be executed, indicating that the tuple is empty.
- We use the same approach to check if the non_empty_tuple is empty. Since it contains elements and evaluates to True, the second print statement will be executed, indicating that the tuple is not empty.

### 15. Create a nested tuple.

In [120]:
# Step 1: Create a nested tuple
nested_tuple = ((1, 2, 3), ('a', 'b', 'c'), (True, False))

# Step 2: Print the nested tuple
print("Nested tuple:", nested_tuple)

Nested tuple: ((1, 2, 3), ('a', 'b', 'c'), (True, False))


- We create a nested tuple named nested_tuple that contains three tuples as its elements. Each of these inner tuples can have different data types.
- We print the nested tuple to see its structure.

### 16. Access the first element of a nested tuple.

In [121]:
# Step 1: Create a nested tuple
nested_tuple = ((1, 2, 3), ('a', 'b', 'c'), (True, False))

# Step 2: Access the first element of the nested tuple
first_element = nested_tuple[0]

# Step 3: Print the first element
print("First element of the nested tuple:", first_element)

First element of the nested tuple: (1, 2, 3)


- We start by creating a nested tuple named nested_tuple that contains three inner tuples.
- We use indexing [0] to access the first element of the nested_tuple. This element is itself a tuple (1, 2, 3).
- We print the first element to see its contents.

### 17. Create a tuple with a single element.

In [122]:
# Step 1: Create a tuple with a single element
single_element_tuple = (42,)  # Note the trailing comma

# Step 2: Print the single element tuple
print("Single element tuple:", single_element_tuple)

Single element tuple: (42,)


- We create a tuple named single_element_tuple with a single element. The key here is to include a trailing comma after the element, which informs Python that you want to create a tuple with one element.
- We print the single element tuple to see its contents.

### 18. Compare two tuples.

In [123]:
# Step 1: Create two tuples
tuple1 = (1, 2, 3)
tuple2 = (1, 2, 4)

# Step 2: Compare the two tuples using comparison operators
print("tuple1 == tuple2:", tuple1 == tuple2)  # Equality check
print("tuple1 != tuple2:", tuple1 != tuple2)  # Inequality check
print("tuple1 < tuple2:", tuple1 < tuple2)    # Less than check
print("tuple1 <= tuple2:", tuple1 <= tuple2)  # Less than or equal to check
print("tuple1 > tuple2:", tuple1 > tuple2)    # Greater than check
print("tuple1 >= tuple2:", tuple1 >= tuple2)  # Greater than or equal to check

tuple1 == tuple2: False
tuple1 != tuple2: True
tuple1 < tuple2: True
tuple1 <= tuple2: True
tuple1 > tuple2: False
tuple1 >= tuple2: False


We create two tuples named tuple1 and tuple2.
We use various comparison operators to compare the elements of the two tuples:
- tuple1 == tuple2 checks if the tuples are equal element-wise.
- tuple1 != tuple2 checks if the tuples are not equal element-wise.
- tuple1 < tuple2 checks if tuple1 is lexicographically less than tuple2.
- tuple1 <= tuple2 checks if tuple1 is lexicographically less than or equal to tuple2.
- tuple1 > tuple2 checks if tuple1 is lexicographically greater than tuple2.
- tuple1 >= tuple2 checks if tuple1 is lexicographically greater than or equal to tuple2.

### 19. Delete a tuple.

In [124]:
# Step 1: Create a tuple
my_tuple = (1, 2, 3, 4, 5)

# Step 2: Delete the tuple using the 'del' statement
del my_tuple

# Step 3: Try to access the tuple (will raise a NameError)
print(my_tuple)

NameError: name 'my_tuple' is not defined

- We start by creating a tuple named my_tuple with some elements.
- We use the del statement to delete the entire tuple.
- When you try to access the tuple after deleting it, you will get a NameError because the tuple no longer exists.

### 20. Slice a tuple.

In [ ]:
# Step 1: Create a tuple
my_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# Step 2: Slice the tuple to get a portion of it
sliced_tuple = my_tuple[2:6]  # Elements from index 2 to 5 (end index is exclusive)

# Step 3: Print the sliced tuple
print("Sliced tuple:", sliced_tuple)

- We start by creating a tuple named my_tuple with some elements.
- We use slicing [start:end] to extract a portion of the tuple. In this example, my_tuple[2:6] gives us elements from index 2 to 5 (end index is exclusive).
- We print the sliced tuple to see its contents.

### 21. Find the maximum value in a tuple.

In [125]:
# Step 1: Create a tuple
my_tuple = (10, 20, 5, 45, 30)

# Step 2: Find the maximum value in the tuple using the 'max()' function
max_value = max(my_tuple)

# Step 3: Print the maximum value
print("Maximum value:", max_value)

Maximum value: 45


- We start by creating a tuple named my_tuple with some numeric elements.
- We use the max() function and pass the my_tuple as an argument. This function returns the maximum value from the tuple.
- We print the maximum value.

### 22. Find the minimum value in a tuple.

In [126]:
# Step 1: Create a tuple
my_tuple = (10, 20, 5, 45, 30)

# Step 2: Find the minimum value in the tuple using the 'min()' function
min_value = min(my_tuple)

# Step 3: Print the minimum value
print("Minimum value:", min_value)

Minimum value: 5


- We start by creating a tuple named my_tuple with some numeric elements.
- We use the min() function and pass the my_tuple as an argument. This function returns the minimum value from the tuple.
- We print the minimum value.

### 23. Convert a string to a tuple of characters.

In [127]:
# Step 1: Create a string
my_string = "Hello, World!"

# Step 2: Convert the string to a tuple of characters
tuple_of_characters = tuple(my_string)

# Step 3: Print the tuple of characters
print("Tuple of characters:", tuple_of_characters)

Tuple of characters: ('H', 'e', 'l', 'l', 'o', ',', ' ', 'W', 'o', 'r', 'l', 'd', '!')


- We start by creating a string named my_string.
- We use the tuple() constructor and pass the string my_string as an argument. This constructor converts the string into a tuple of individual characters.
- We print the resulting tuple of characters.

### 24. Convert a tuple of characters to a string.

In [128]:
# Step 1: Create a tuple of characters
tuple_of_characters = ('H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd', '!')

# Step 2: Convert the tuple of characters to a string using the 'join()' method
string_from_tuple = ''.join(tuple_of_characters)

# Step 3: Print the resulting string
print("String from tuple:", string_from_tuple)

String from tuple: Hello World!


- We start by creating a tuple named tuple_of_characters containing individual characters.
- We use the join() method, which is called on an empty string (''), to join the characters from the tuple and create a single string.
- We print the resulting string.

### 25. Create a tuple from multiple data types.

In [129]:
# Creating a tuple with elements of different data types
mixed_tuple = (1, "hello", 3.14, True)

# Printing the tuple
print(mixed_tuple)

(1, 'hello', 3.14, True)


- The mixed_tuple contains four elements of different data types: an integer, a string, a float, and a boolean. You can combine various data types in a tuple in the same way.

### 26. Check if two tuples are identical.

In [130]:
# Step 1: Create two tuples
tuple1 = (1, 2, 3)
tuple2 = (1, 2, 3)
tuple3 = (4, 5, 6)

# Step 2: Compare the tuples for identity using the equality operator
are_identical1 = tuple1 == tuple2
are_identical2 = tuple1 == tuple3

# Step 3: Print the results
print("tuple1 and tuple2 are identical:", are_identical1)
print("tuple1 and tuple3 are identical:", are_identical2)

tuple1 and tuple2 are identical: True
tuple1 and tuple3 are identical: False


- We create three tuples named tuple1, tuple2, and tuple3 with different elements.
- We use the equality operator == to compare the tuples for identity. If all corresponding elements are the same, the tuples are considered identical.
- We print the results of the comparisons.

### 27. Sort the elements of a tuple.

In [131]:
# Step 1: Create a tuple
my_tuple = (5, 2, 8, 1, 3)

# Step 2: Convert the tuple to a list, sort the list, and convert it back to a tuple
sorted_tuple = tuple(sorted(my_tuple))

# Step 3: Print the sorted tuple
print("Sorted tuple:", sorted_tuple)


Sorted tuple: (1, 2, 3, 5, 8)


- We start by creating a tuple named my_tuple with some numeric elements.
- We use the sorted() function to sort the elements of the tuple. The sorted() function returns a sorted list.
- We use the tuple() constructor to convert the sorted list back into a tuple.
- We print the sorted tuple.

### 28. Convert a tuple of integers to a tuple of strings.

In [132]:
# Step 1: Create a tuple of integers
tuple_of_integers = (1, 2, 3, 4, 5)

# Step 2: Convert the tuple of integers to a tuple of strings using a list comprehension
tuple_of_strings = tuple(str(item) for item in tuple_of_integers)

# Step 3: Print the tuple of strings
print("Tuple of strings:", tuple_of_strings)

Tuple of strings: ('1', '2', '3', '4', '5')


- We start by creating a tuple named tuple_of_integers containing integer elements.
- We use a list comprehension to iterate through each integer in the tuple and convert it to a string using the str() function. The list comprehension generates a list of strings.
- We convert the list of strings to a tuple using the tuple() constructor.
- We print the resulting tuple of strings.

### 29. Convert a tuple of strings to a tuple of integers.

In [133]:
# Step 1: Create a tuple of strings
tuple_of_strings = ('10', '20', '30', '40', '50')

# Step 2: Convert the tuple of strings to a tuple of integers using a list comprehension
tuple_of_integers = tuple(int(item) for item in tuple_of_strings)

# Step 3: Print the tuple of integers
print("Tuple of integers:", tuple_of_integers)

Tuple of integers: (10, 20, 30, 40, 50)


- We start by creating a tuple named tuple_of_strings containing string elements.
- We use a list comprehension to iterate through each string in the tuple and convert it to an integer using the int() function. The list comprehension generates a list of integers.
- We convert the list of integers to a tuple using the tuple() constructor.
- We print the resulting tuple of integers.

### 30. Merge two tuples.

In [134]:
# Step 1: Create two tuples
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

# Step 2: Merge the two tuples using the '+' operator
merged_tuple = tuple1 + tuple2

# Step 3: Print the merged tuple
print("Merged tuple:", merged_tuple)

Merged tuple: (1, 2, 3, 4, 5, 6)


- We start by creating two tuples named tuple1 and tuple2.
- We use the + operator to merge the two tuples, resulting in a new tuple named merged_tuple.
- We print the merged tuple.

### 31. Flatten a nested tuple.

In [135]:
# Recursive function to flatten a nested tuple
def flatten_tuple(nested_tuple):
    flattened = []
    for item in nested_tuple:
        if isinstance(item, tuple):
            flattened.extend(flatten_tuple(item))
        else:
            flattened.append(item)
    return flattened

# Step 1: Create a nested tuple
nested_tuple = ((1, 2), (3, 4, 5), (6, (7, 8)))

# Step 2: Flatten the nested tuple
flattened_tuple = tuple(flatten_tuple(nested_tuple))

# Step 3: Print the flattened tuple
print("Flattened tuple:", flattened_tuple)

Flattened tuple: (1, 2, 3, 4, 5, 6, 7, 8)


- We define a recursive function named flatten_tuple that takes a nested tuple as input and returns a list of its flattened elements.
- Inside the function, we iterate through each element in the nested tuple. If an element is itself a tuple, we recursively call the flatten_tuple function on that element and extend the flattened list with its flattened elements. If the element is not a tuple, we append it to the flattened list.
- We create a nested tuple named nested_tuple with varying levels of nesting.
- We use the flatten_tuple function to convert the nested tuple into a flattened list and then convert the list back to a tuple using the tuple() constructor.
- We print the resulting flattened tuple.

### 32. Create a tuple of the first 5 prime numbers.

In [136]:
# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate the first 5 prime numbers
prime_numbers_list = [num for num in range(2, 100) if is_prime(num)][:5]

# Convert the list to a tuple
prime_numbers_tuple = tuple(prime_numbers_list)

# Print the tuple of prime numbers
print("Tuple of the first 5 prime numbers:", prime_numbers_tuple)

Tuple of the first 5 prime numbers: (2, 3, 5, 7, 11)


- We define a function is_prime(num) that checks whether a given number is prime. It returns True if the number is prime and False otherwise.
- We use a list comprehension to generate a list of prime numbers. The list comprehension iterates through numbers from 2 to 99 and selects the first 5 prime numbers using the is_prime() function.
- We convert the list of prime numbers to a tuple using the tuple() constructor.
- We print the resulting tuple of the first 5 prime numbers.

### 3. Check if a tuple is a palindrome.

In [137]:
# Function to check if a tuple is a palindrome
def is_palindrome(tup):
    return tup == tup[::-1]

# Create tuples for testing
palindrome_tuple = (1, 2, 3, 2, 1)
non_palindrome_tuple = (1, 2, 3, 4, 5)

# Check if the tuples are palindromes
is_palindrome1 = is_palindrome(palindrome_tuple)
is_palindrome2 = is_palindrome(non_palindrome_tuple)

# Print the results
print("palindrome_tuple is a palindrome:", is_palindrome1)
print("non_palindrome_tuple is a palindrome:", is_palindrome2)

palindrome_tuple is a palindrome: True
non_palindrome_tuple is a palindrome: False


- We define a function is_palindrome(tup) that takes a tuple as input and returns True if the tuple is a palindrome (reads the same forwards and backwards), and False otherwise.
- Inside the function, we compare the input tuple tup with its reversed version using the slicing notation tup[::-1].
- We create two tuples, palindrome_tuple and non_palindrome_tuple, for testing.
- We call the is_palindrome() function on each tuple to check if they are palindromes.
- We print the results of the palindrome checks.

### 34. Create a tuple of squares of numbers from 1 to 5.

In [138]:
# Create a tuple of squares using a list comprehension
squares_tuple = tuple(x ** 2 for x in range(1, 6))

# Print the tuple of squares
print("Tuple of squares:", squares_tuple)

Tuple of squares: (1, 4, 9, 16, 25)


- We use a list comprehension to calculate the squares of numbers from 1 to 5. - The expression x ** 2 calculates the square of each number x.
- We convert the list of squares to a tuple using the tuple() constructor.
- We print the resulting tuple of squares.

### 35. Filter out all even numbers from a tuple.

In [139]:
# Create a tuple
original_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# Filter out even numbers using a list comprehension
filtered_tuple = tuple(num for num in original_tuple if num % 2 != 0)

# Print the filtered tuple
print("Filtered tuple:", filtered_tuple)

Filtered tuple: (1, 3, 5, 7, 9)


- We start by creating a tuple named original_tuple with some numeric elements.
- We use a list comprehension to iterate through each number in the original_tuple. The conditional statement num % 2 != 0 checks if the number is not even (i.e., it's odd).
- Only odd numbers are included in the list comprehension, and we convert the resulting list to a tuple using the tuple() constructor.
- We print the resulting filtered tuple.

### 36. Multiply all elements in a tuple by 2.

In [140]:
# Create a tuple
original_tuple = (1, 2, 3, 4, 5)

# Multiply all elements by 2 using a list comprehension and convert to a tuple
doubled_tuple = tuple(num * 2 for num in original_tuple)

# Print the doubled tuple
print("Doubled tuple:", doubled_tuple)

Doubled tuple: (2, 4, 6, 8, 10)


- We start by creating a tuple named original_tuple with some numeric elements.
- We use a list comprehension to iterate through each number in the original_tuple and multiply it by 2.
- The num * 2 expression calculates the doubled value for each element.
- We convert the resulting list of doubled values to a tuple using the tuple() constructor.
- We print the resulting doubled tuple.

### 37. Create a tuple of random numbers.

In [141]:
import random

# Create a tuple of random numbers using a list comprehension
random_tuple = tuple(random.randint(1, 100) for _ in range(10))  # Generating 10 random numbers between 1 and 100

# Print the tuple of random numbers
print("Random tuple:", random_tuple)

Random tuple: (27, 17, 35, 98, 40, 13, 85, 47, 52, 94)


- We use a list comprehension to generate 10 random numbers between 1 and 100 using the random.randint() function.
- The _ variable is used as a placeholder because we're not using the loop variable in the list comprehension.
- We convert the resulting list of random numbers to a tuple using the tuple() constructor.
- We print the resulting random tuple.

### 38. Check if a tuple is sorted.

In [142]:
# Function to check if a tuple is sorted
def is_sorted(tup):
    for i in range(len(tup) - 1):
        if tup[i] > tup[i + 1]:
            return False
    return True

# Create tuples for testing
sorted_tuple = (1, 2, 3, 4, 5)
unsorted_tuple = (5, 3, 1, 4, 2)

# Check if the tuples are sorted
is_sorted1 = is_sorted(sorted_tuple)
is_sorted2 = is_sorted(unsorted_tuple)

# Print the results
print("sorted_tuple is sorted:", is_sorted1)
print("unsorted_tuple is sorted:", is_sorted2)

sorted_tuple is sorted: True
unsorted_tuple is sorted: False


- We define a function is_sorted(tup) that takes a tuple as input and returns True if the tuple is sorted in non-decreasing order, and False otherwise.
- Inside the function, we iterate through the tuple's elements using a loop. We compare each element with the next one. If we find an element that is greater than the next one, the tuple is not sorted.
- We create two tuples, sorted_tuple and unsorted_tuple, for testing.
- We call the is_sorted() function on each tuple to check if they are sorted.
- We print the results of the sorted checks.

### 39. Rotate a tuple to the left by `n` positions.

In [143]:
def rotate_tuple_left(tup, n):
    n = n % len(tup)  # Ensure n is within the range of tuple length
    rotated_tuple = tup[n:] + tup[:n]  # Rotate the tuple
    return rotated_tuple

# Example tuple
my_tuple = (1, 2, 3, 4, 5)
n_positions = 2
result = rotate_tuple_left(my_tuple, n_positions)
print(result)

(3, 4, 5, 1, 2)


- Define a function named rotate_tuple_left that takes two parameters: tup (the tuple to rotate) and n (the number of positions to rotate by).
- Inside the function, calculate n modulo len(tup) to ensure that n is within the range of the tuple length. This step is necessary to handle cases where n is greater than the tuple length.
- Use slicing to create a new tuple named rotated_tuple by concatenating two parts:
  - tup[n:] extracts the elements from index n to the end of the tuple.
  - tup[:n] extracts the elements from the start of the tuple up to index n-1.
- The concatenated parts create the rotated tuple.
- Return the rotated_tuple from the function.
- Define an example my_tuple containing elements (1, 2, 3, 4, 5) and n_positions as 2 for rotation.
- Call the rotate_tuple_left function with the my_tuple and n_positions, and store the result in the result variable.
- Print the result to see the tuple after left rotation by n_positions.

### 40. Rotate a tuple to the right by `n` positions.

In [144]:
def rotate_tuple_right(tup, n):
    n = n % len(tup)  # Ensure n is within the range of tuple length
    rotated_tuple = tup[-n:] + tup[:-n]  # Rotate the tuple
    return rotated_tuple

# Example tuple
my_tuple = (1, 2, 3, 4, 5)
n_positions = 2
result = rotate_tuple_right(my_tuple, n_positions)
print(result)

(4, 5, 1, 2, 3)


- Define a function named rotate_tuple_right that takes two parameters: tup (the tuple to rotate) and n (the number of positions to rotate by).
- Inside the function, calculate n modulo len(tup) to ensure that n is within the range of the tuple length.
- Use slicing to create a new tuple named rotated_tuple by concatenating two parts:
  - tup[-n:] extracts the last n elements of the tuple.
  - tup[:-n] extracts the elements from the start of the tuple up to index -(n+1).
- The concatenated parts create the rotated tuple.
- Return the rotated_tuple from the function.
- Define an example my_tuple containing elements (1, 2, 3, 4, 5) and n_positions as 2 for rotation.
- Call the rotate_tuple_right function with the my_tuple and n_positions, and store the result in the result variable.
- Print the result to see the tuple after right rotation by n_positions.

### 41. Create a tuple of the first 5 Fibonacci numbers.

In [145]:
# Define a function to generate the first n Fibonacci numbers
def generate_fibonacci(n):
    fibonacci = [0, 1]  # Initialize the list with the first two Fibonacci numbers
    while len(fibonacci) < n:  # Continue generating Fibonacci numbers until the list has n elements
        next_number = fibonacci[-1] + fibonacci[-2]  # Calculate the next Fibonacci number
        fibonacci.append(next_number)  # Add the next Fibonacci number to the list
    return tuple(fibonacci)  # Convert the list to a tuple and return it

# Call the generate_fibonacci function to create a tuple of the first 5 Fibonacci numbers
fibonacci_tuple = generate_fibonacci(5)

# Print the resulting tuple
print(fibonacci_tuple)

(0, 1, 1, 2, 3)


- Create a function named generate_fibonacci that takes a parameter n, which represents the number of Fibonacci numbers to generate.
- Create a list called fibonacci and initialize it with the first two Fibonacci numbers [0, 1].
- Use a while loop to continue generating Fibonacci numbers until the length of the fibonacci list is less than n.
- Calculate the next Fibonacci number: Calculate the next Fibonacci number by adding the last two numbers in the fibonacci list. We use negative indexing to access the last and second-to-last elements.
- Add the next Fibonacci number to the list: Append the next_number to the end of the fibonacci list.
- Convert the list to a tuple and return it: Call the generate_fibonacci function with an argument of 5 to generate the first 5 Fibonacci numbers and store the resulting tuple in the variable fibonacci_tuple.
- Print the fibonacci_tuple, which contains the first 5 Fibonacci numbers.

### 42. Create a tuple from user input.

In [147]:
# Taking user input for creating a tuple
input_str = input("Enter elements separated by commas: ")

# Splitting the input string into a list of strings
input_list = input_str.split(',')

# Converting the list of strings to a tuple
user_tuple = tuple(input_list)

# Printing the created tuple
print("User input tuple:", user_tuple)

Enter elements separated by commas:  Car,Bus


User input tuple: ('Car', 'Bus')


In this code, the user is prompted to enter elements separated by commas. The input is split into a list of strings using the split() method, and then converted into a tuple using the tuple() constructor. Finally, the created tuple is printed to the console.

### 43. Swap two elements in a tuple.

In [148]:
# Create a tuple
my_tuple = (1, 2, 3, 4, 5)

# Swap elements at indices 1 and 3
index1 = 1
index2 = 3
swapped_tuple = tuple(
    my_tuple[i] if i not in (index1, index2) else
    my_tuple[index2] if i == index1 else
    my_tuple[index1]
    for i in range(len(my_tuple))
)

# Print the swapped tuple
print("Swapped tuple:", swapped_tuple)

Swapped tuple: (1, 4, 3, 2, 5)


- We start by creating a tuple named my_tuple with some elements.
- We specify the indices (index1 and index2) of the elements we want to swap.
- We use a list comprehension to create a new tuple. For each index i in the range of the tuple's length, we decide which value to include in the new tuple:
  - If i is not index1 or index2, we include the original value from my_tuple.
  - If i is index1, we include the value at index2 from my_tuple.
  - If i is index2, we include the value at index1 from my_tuple.
- We convert the list comprehension to a tuple using the tuple() constructor.
- We print the resulting swapped tuple.

### 44. Reverse the elements of a tuple.

In [149]:
# Create a tuple
my_tuple = (1, 2, 3, 4, 5)

# Reverse the elements using slicing
reversed_tuple = my_tuple[::-1]

# Print the reversed tuple
print("Reversed tuple:", reversed_tuple)

Reversed tuple: (5, 4, 3, 2, 1)


- We start by creating a tuple named my_tuple with some elements.
- We use slicing with the notation my_tuple[::-1] to create a new tuple with the elements in reverse order.
- The -1 step in the slice indicates that we're stepping backwards through the tuple.
- We print the resulting reversed tuple.

### 45. Create a tuple of the first `n` powers of 2.

In [150]:
# Define the value of n
n = 5

# Create a tuple of the first n powers of 2 using a list comprehension
powers_of_2_tuple = tuple(2 ** i for i in range(n))

# Print the tuple of powers of 2
print("Tuple of the first", n, "powers of 2:", powers_of_2_tuple)

Tuple of the first 5 powers of 2: (1, 2, 4, 8, 16)


- We define the value of n to determine how many powers of 2 you want to generate.
- We use a list comprehension to calculate the powers of 2 using the expression 2 ** i where i varies from 0 to n-1.
- We convert the resulting list of powers of 2 to a tuple using the tuple() constructor.
- We print the resulting tuple of powers of 2.

### 46. Find the longest string in a tuple of strings.

In [151]:
# Create a tuple of strings
string_tuple = ("apple", "banana", "grape", "kiwi", "watermelon")

# Find the longest string in the tuple
longest_string = max(string_tuple, key=len)

# Print the longest string
print("Longest string:", longest_string)

Longest string: watermelon


- We start by creating a tuple named string_tuple containing some string elements.
- We use the max() function with the key parameter set to len to find the longest string in the tuple based on the length of each string.
- The key=len argument tells max() to compare the strings based on their lengths.
- We print the resulting longest string

### 47. Find the shortest string in a tuple of strings.

In [152]:
# Create a tuple of strings
string_tuple = ("apple", "banana", "grape", "kiwi", "watermelon")

# Find the shortest string in the tuple
shortest_string = min(string_tuple, key=len)

# Print the shortest string
print("Shortest string:", shortest_string)

Shortest string: kiwi


- We start by creating a tuple named string_tuple containing some string elements.
- We use the min() function with the key parameter set to len to find the shortest string in the tuple based on the length of each string.
- The key=len argument tells min() to compare the strings based on their lengths.
- We print the resulting shortest string.

### 48. Create a tuple of the first `n` triangular numbers.

In [153]:
# Define the value of n
n = 5

# Create a tuple of the first n triangular numbers using a list comprehension
triangular_numbers_tuple = tuple((i * (i + 1)) // 2 for i in range(1, n + 1))

# Print the tuple of triangular numbers
print("Tuple of the first", n, "triangular numbers:", triangular_numbers_tuple)

Tuple of the first 5 triangular numbers: (1, 3, 6, 10, 15)


- We define the value of n to determine how many triangular numbers you want to generate.
- We use a list comprehension to calculate the triangular numbers using the expression (i * (i + 1)) // 2 where i varies from 1 to n.
- We convert the resulting list of triangular numbers to a tuple using the tuple() constructor.
- We print the resulting tuple of triangular numbers.

### 49. Check if a tuple contains another tuple as a subsequence.

In [154]:
# Function to check if a tuple contains another tuple as a subsequence
def contains_subsequence(main_tuple, sub_tuple):
    sub_length = len(sub_tuple)
    for i in range(len(main_tuple) - sub_length + 1):
        if main_tuple[i:i+sub_length] == sub_tuple:
            return True
    return False

# Main tuple
main_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9)

# Subsequence tuple
sub_tuple = (3, 4, 5)

# Check if the main tuple contains the subsequence tuple
contains_subseq = contains_subsequence(main_tuple, sub_tuple)

# Print the result
print("Main tuple contains subsequence tuple:", contains_subseq)

Main tuple contains subsequence tuple: True


- We define a function contains_subsequence(main_tuple, sub_tuple) that takes two tuples as input and returns True if the main_tuple contains the sub_tuple as a subsequence, and False otherwise.
- Inside the function, we calculate the length of the sub_tuple.
- We iterate through the main_tuple using a loop that runs until the end of the main tuple minus the length of the subtuple. This is because there's no need to compare subsequences if there isn't enough space left in the main tuple.
- Within the loop, we check if the slice of the main_tuple from index i to i + sub_length is equal to the sub_tuple. If it is, then the main_tuple contains the sub_tuple as a subsequence.
- We return True if the subsequence is found, and if the loop completes without finding the subsequence, we return False.
- We create the main tuple and subsequence tuple for testing.
- We call the contains_subsequence() function and store the result in the contains_subseq variable.
- We print the result.

### 50. Create a tuple of alternating 1s and 0s of length `n`.

In [155]:
# Define the value of n
n = 10

# Create a tuple of alternating 1s and 0s using a list comprehension
alternating_tuple = tuple(i % 2 for i in range(n))

# Print the tuple of alternating 1s and 0s
print("Tuple of alternating 1s and 0s:", alternating_tuple)

Tuple of alternating 1s and 0s: (0, 1, 0, 1, 0, 1, 0, 1, 0, 1)


- We define the value of n to determine the length of the tuple you want to generate.
- We use a list comprehension to generate the alternating 1s and 0s pattern using the expression i % 2, which produces 0 for even i values and 1 for odd i values.
- We convert the resulting list of alternating 1s and 0s to a tuple using the tuple() constructor.
- We print the resulting tuple of alternating 1s and 0s.

## **Set based problems:**

---


### 1. Create a set with integers from 1 to 5

In [156]:
# Step 1: Create an empty set
my_set = set()

# Step 2: Add integers from 1 to 5 to the set
my_set.add(1)
my_set.add(2)
my_set.add(3)
my_set.add(4)
my_set.add(5)

# Step 3: Print the final set
print(my_set)## Set based problems:

{1, 2, 3, 4, 5}


- my_set = set(): In this step, an empty set is created using the set() constructor. This sets up the initial container for our set of integers.

- my_set.add(1), my_set.add(2), ...: Here, each add() method is used to add individual integers from 1 to 5 to the set. Since sets automatically handle uniqueness, duplicates are automatically avoided.

- print(my_set): Finally, the contents of the set are printed. The output will be the set of integers from 1 to 5 in an arbitrary order, due to sets being unordered collections.

### 2. Add an element to a set

In [157]:
# Step 1: Create a set
my_set = {1, 2, 3, 4, 5}

# Step 2: Display the original set
print("Original set:", my_set)

# Step 3: Add an element to the set
element_to_add = 6
my_set.add(element_to_add)

# Step 4: Display the modified set
print("Set after adding element:", my_set)

Original set: {1, 2, 3, 4, 5}
Set after adding element: {1, 2, 3, 4, 5, 6}


- Create a set: We start by creating a set called my_set containing integers from 1 to 5 using curly braces {}.

- Display the original set: We print the original set using the print() function. This step is just to show the initial contents of the set.

- Add an element to the set: We define a variable element_to_add and set its value to the integer 6. Then, we use the add() method of the set (my_set) to add the element_to_add to the set.

- Display the modified set: After adding the element, we print the modified set using the print() function to show that the new element (6) has been added.

### 3. Remove an element from a set.


In [158]:
# Step 1: Create a set with some elements
my_set = {1, 2, 3, 4, 5}

# Step 2: Print the original set
print("Original Set:", my_set)

# Step 3: Choose an element to remove
element_to_remove = 3

# Step 4: Use the remove() method to remove the chosen element
# Note: If the element is not present in the set, remove() raises a KeyError.
my_set.remove(element_to_remove)

# Step 5: Print the modified set after removal
print("Set after removing", element_to_remove, ":", my_set)

Original Set: {1, 2, 3, 4, 5}
Set after removing 3 : {1, 2, 4, 5}


- We start by creating a set my_set with elements 1, 2, 3, 4, and 5.
- We print the original set using print("Original Set:", my_set).
- We choose an element to remove. In this example, we're removing the element 3.
- We use the remove() method on the set to remove the chosen element. In this case, my_set.remove(3) will remove the element 3 from the set.
- If the element is not present in the set, this line of code would raise a KeyError. This is something to keep in mind when using the remove() method.
- Finally, we print the modified set after the removal using print("Set after removing", element_to_remove, ":", my_set).

### 4. Check if an element exists in a set.


In [159]:
# Step 1: Create a set with some elements
my_set = {1, 3, 5, 7, 9}

# Step 2: Ask the user for the element they want to check
element_to_check = int(input("Enter the element to check: "))

# Step 3: Use the "in" keyword to check if the element exists in the set
if element_to_check in my_set:
    # Step 4: If the element exists in the set, print a message
    print(f"{element_to_check} exists in the set.")
else:
    # Step 5: If the element does not exist in the set, print a message
    print(f"{element_to_check} does not exist in the set.")

Enter the element to check:  5


5 exists in the set.


- We start by creating a set called my_set with some sample elements (in this case, {1, 3, 5, 7, 9}).

- We ask the user to input the element they want to check by using the input() function. The input is read as a string, so we convert it to an integer using int().

- We use the in keyword to check if the entered element_to_check exists in the my_set.

- If the element exists in the set, the code inside the if block is executed. We use string formatting (f"...") to print a message indicating that the element exists in the set.

- If the element does not exist in the set, the code inside the else block is executed. We again use string formatting to print a message indicating that the element does not exist in the set.

### 5. Find the length of a set without using the `len()` function

In [168]:
# Create a set with some elements
my_set = {1, 2, 3, 4, 5}

# Initialize a variable to count the elements in the set
count = 0

# Iterate through each element in the set
for _ in my_set:
    # Increase the count by 1 for each element
    count += 1

# Print the count, which is the length of the set
print("Length of the set:", count)

Length of the set: 5


- We start by creating a set called my_set containing some elements.
- Next, we initialize a variable count to keep track of the number of elements in the set. This variable will act as our manual counter for the length.
- We use a for loop to iterate through each element in the my_set. The underscore _ is a common convention to represent a variable whose value isn't going to be used within the loop. Since we're interested in the count, we don't need the individual elements themselves.
- Inside the loop, for each iteration, we increase the count variable by 1. This simulates counting the elements as we iterate through them.
- Once the loop finishes iterating through all the elements, we have the total count stored in the count variable.
- Finally, we print the value of count, which represents the length of the set.

### 6. Clear all elements from a set.

In [169]:
# Step 1: Create a set with some elements
my_set = {1, 2, 3, 4, 5}

# Step 2: Display the original set
print("Original set:", my_set)

# Step 3: Clear all elements from the set using the clear() method
my_set.clear()

# Step 4: Display the set after clearing
print("Set after clearing:", my_set)


Original set: {1, 2, 3, 4, 5}
Set after clearing: set()


- We create a set named my_set containing the integers from 1 to 5 using the curly braces {}.
- We use the print() function to display the contents of the original set my_set.
- We call the clear() method on the my_set set. This method removes all elements from the set, effectively emptying it.
- We again use the print() function to display the contents of the set after it has been cleared. Since all elements have been removed, the set will be empty, and this will be reflected in the output.

### 7. Create a set of even numbers from 1 to 10

In [170]:
# Step 1: Initialize an empty set
even_numbers_set = set()

# Step 2: Iterate through numbers from 1 to 10
for num in range(1, 11):
    # Step 3: Check if the number is even
    if num % 2 == 0:
        # Step 4: Add the even number to the set
        even_numbers_set.add(num)

# Step 5: Print the set of even numbers
print(even_numbers_set)

{2, 4, 6, 8, 10}


- We start by initializing an empty set called even_numbers_set to store the even numbers.
- We use a for loop to iterate through numbers from 1 to 10 (inclusive).
- Inside the loop, we use the modulo operator % to check if the current number num is even. If the remainder of num divided by 2 is 0, then it's even.
- If the number is even, we add it to the even_numbers_set using the add() method.
- Finally, we print the set of even numbers.

### 8. Create a set of odd numbers from 1 to 10

In [171]:
# Step 1: Initialize an empty set to store odd numbers.
odd_numbers_set = set()

# Step 2: Iterate through numbers from 1 to 10.
for num in range(1, 11):
    # Step 3: Check if the current number is odd.
    if num % 2 != 0:
        # Step 4: If the number is odd, add it to the set.
        odd_numbers_set.add(num)

# Step 5: Print the final set of odd numbers.
print(odd_numbers_set)

{1, 3, 5, 7, 9}


- We start by initializing an empty set called odd_numbers_set using the set() constructor.
- We use a for loop to iterate through numbers from 1 to 10 using the range() function. The loop variable num takes values from 1 to 10.
- Within the loop, we use the modulo operator % to check if the current number (num) is odd. If the remainder of dividing num by 2 is not equal to 0, then the number is odd.
- If the current number is odd (as determined in the previous step), we use the add() method to add that number to the odd_numbers_set.
- Finally, after the loop completes, we print the odd_numbers_set, which contains the odd numbers from 1 to 10.

### 9. Find the union of two sets

In [172]:
# Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Find the union of the two sets using the `union()` method
union_result = set1.union(set2)

# Print the original sets and their union
print("Set 1:", set1)
print("Set 2:", set2)
print("Union of Set 1 and Set 2:", union_result)

Set 1: {1, 2, 3, 4, 5}
Set 2: {4, 5, 6, 7, 8}
Union of Set 1 and Set 2: {1, 2, 3, 4, 5, 6, 7, 8}


- We start by defining two sets, set1 and set2, each containing distinct elements.
- We use the .union() method to find the union of the two sets. This method returns a new set containing all the unique elements present in either of the sets.
- The result of the union operation is stored in the union_result variable.
- We print out the original sets using print() statements.
- We also print out the result of the union using the union_result variable.

### 10. Find the intersection of two sets

In [173]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}

# Find the intersection using the intersection() method
intersection_result = set1.intersection(set2)

# Print the original sets and the intersection
print("Set 1:", set1)
print("Set 2:", set2)
print("Intersection:", intersection_result)

Set 1: {1, 2, 3, 4, 5}
Set 2: {3, 4, 5, 6, 7}
Intersection: {3, 4, 5}


- We start by creating two sets set1 and set2. These sets contain distinct elements.

- We use the intersection() method on the set1 set and provide set2 as an argument. This method returns a new set containing the common elements between the two sets.

- We store the result of the intersection operation in the intersection_result variable.

- Finally, we use the print() function to display the original sets (set1 and set2) along with the computed intersection (intersection_result).

### 11. Find the difference between two sets.

In [174]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}

# Find the difference between the sets using the difference() method
difference_set = set1.difference(set2)

# Print the original sets and the difference set
print("Set 1:", set1)
print("Set 2:", set2)
print("Difference:", difference_set)

Set 1: {1, 2, 3, 4, 5}
Set 2: {3, 4, 5, 6, 7}
Difference: {1, 2}


- We start by creating two sets: set1 and set2. These sets contain some integers.
- We use the .difference() method to find the difference between set1 and set2. - The difference between two sets contains all the elements that are present in the first set but not in the second set.
- We assign the result of the difference operation to the variable difference_set.
- We use the print() function to display the original sets (set1 and set2) and the calculated difference set (difference_set).

### 12. Check if a set is a subset of another set.

In [175]:
# Define the two sets
set1 = {1, 2, 3}
set2 = {1, 2, 3, 4, 5}

# Use the "issubset()" method to check if set1 is a subset of set2
is_subset = set1.issubset(set2)

# Print the result
print("Is set1 a subset of set2:", is_subset)

Is set1 a subset of set2: True


- We start by defining two sets, set1 and set2, using the curly braces {} notation.
- The issubset() method is used to check if set1 is a subset of set2. This method returns True if all the elements of set1 are present in set2, otherwise, it returns False.
- We store the result of the subset check in the variable is_subset.
- Finally, we use the print() function to display whether set1 is a subset of set2. The value of is_subset will be either True or False.

### 13. Check if a set is a superset of another set.

In [176]:
# Create two sets
set1 = {1, 2, 3, 4, 5, 6}
set2 = {3, 4}

# Check if set1 is a superset of set2
is_superset = set1.issuperset(set2)

# Print the result
if is_superset:
    print("set1 is a superset of set2")
else:
    print("set1 is not a superset of set2")

set1 is a superset of set2


- We start by creating two sets:
  - set1 contains the elements {1, 2, 3, 4, 5, 6}.
  - set2 contains the elements {3, 4}.
- The issuperset() method is used to check if set1 is a superset of set2. This method returns True if every element in set2 is also present in set1, and False otherwise.
- We store the result of the issuperset() method in the variable is_superset.
- Next, we use an if statement to check the value of is_superset. If it's True, we print that "set1 is a superset of set2". If it's False, we print that "set1 is not a superset of set2".

### 14. Create a set from a list

In [177]:
# Step 1: Create a list of elements
my_list = [2, 4, 1, 4, 3, 2, 5]

# Step 2: Use the set() constructor to convert the list into a set
# This automatically removes duplicates and creates a set with unique elements
my_set = set(my_list)

# Step 3: Print the original list and the resulting set
print("Original List:", my_list)
print("Set from List:", my_set)

Original List: [2, 4, 1, 4, 3, 2, 5]
Set from List: {1, 2, 3, 4, 5}


- We start by creating a list called my_list containing some elements, including duplicates.
- The set() constructor is used to convert the my_list into a set. This automatically removes duplicate elements, creating a set with only unique elements. The resulting set is stored in the variable my_set.
- Finally, we print both the original list and the set obtained from the list using print() statements.

### 15. Convert a set to a list.

In [178]:
# Step 1: Create a set with some elements
my_set = {3, 1, 4, 1, 5, 9, 2, 6, 5}

# Step 2: Convert the set to a list using the list() function
my_list = list(my_set)

# Now, my_list contains the elements from my_set in list format

# Step 3: Print the original set and the converted list
print("Original Set:", my_set)
print("Converted List:", my_list)

Original Set: {1, 2, 3, 4, 5, 6, 9}
Converted List: [1, 2, 3, 4, 5, 6, 9]


- We start by creating a set called my_set containing several elements, including duplicates. Sets automatically remove duplicates, so even though we have duplicates in the set definition, the resulting set will only contain unique elements.
- To convert the set to a list, we use the list() function. This function takes an iterable (like a set) as its argument and returns a new list containing the same elements in the same order.
- Finally, we print both the original set and the converted list using the print() function. You'll notice that the elements in the list are in the same order as they were in the set, but without duplicates.

### 16. Remove a random element from a set.

In [179]:
import random  # Import the random module

# Create a set with some elements
my_set = {1, 2, 3, 4, 5}

# Display the original set
print("Original set:", my_set)

# Choose a random element from the set using the random.choice() function
random_element = random.choice(list(my_set))

# Remove the chosen random element from the set using the remove() method
my_set.remove(random_element)

# Display the updated set after removing the random element
print("Updated set after removing", random_element, ":", my_set)

Original set: {1, 2, 3, 4, 5}
Updated set after removing 2 : {1, 3, 4, 5}


- `import random`: This line imports the built-in random module, which provides various functions for generating random numbers and performing random selections.
- `my_set = {1, 2, 3, 4, 5}`: Here, we create a set named my_set containing the integers from 1 to 5.
- `print("Original set:", my_set)`: This line prints the original set to the console.
- `random_element = random.choice(list(my_set))`: We convert the set into a list using list(my_set) and then use random.choice() to select a random element from the list. This random element is stored in the variable random_element.
- `my_set.remove(random_element)`: We use the remove() method to remove the randomly chosen element from the set.
- `print("Updated set after removing", random_element, ":", my_set)`: Finally, we print the updated set after removing the random element to the console.

### 17. Pop an element from a set.

In [180]:
# Create a set with some elements
my_set = {1, 2, 3, 4, 5}

# Print the original set
print("Original set:", my_set)

# Pop an element from the set using the pop() method
popped_element = my_set.pop()

# Print the element that was popped
print("Popped element:", popped_element)

# Print the set after popping an element
print("Set after popping:", my_set)

Original set: {1, 2, 3, 4, 5}
Popped element: 1
Set after popping: {2, 3, 4, 5}


- `my_set = {1, 2, 3, 4, 5}`: We create a set named my_set containing integers from 1 to 5.
- `print("Original set:", my_set)`: We print the original set to show its contents before popping an element.
- `popped_element = my_set.pop()`: The pop() method is used to remove and return an arbitrary element from the set. The popped element is stored in the variable popped_element.
- `print("Popped element:", popped_element)`: We print the element that was popped from the set.
- `print("Set after popping:", my_set)`: We print the set after popping an element. Since sets are unordered collections, the specific element popped cannot be predicted. The set will no longer contain the popped element.

### 18. Check if two sets have no elements in common.

In [181]:
# Step 1: Define two sets
set1 = {1, 2, 3, 4}
set2 = {5, 6, 7, 8}

# Step 2: Check if the intersection of the two sets is empty
# The intersection is the set of elements that are common to both sets
common_elements = set1.intersection(set2)

# Step 3: Check if the common_elements set is empty
if not common_elements:
    print("The two sets have no elements in common.")
else:
    print("The two sets have common elements:", common_elements)

The two sets have no elements in common.


- We start by defining two sets set1 and set2 with some elements in each set.
- We use the .intersection() method to find the intersection of set1 and set2. - The result is a set containing elements that are common to both sets.
- We use an if statement to check if the common_elements set is empty. If it's empty, it means the sets have no elements in common, so we print a message indicating that. If the common_elements set is not empty, we print the common elements themselves.

### 19. Find the symmetric difference between two sets.

In [182]:
# Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Calculate the symmetric difference using the ^ operator
symmetric_difference = set1 ^ set2

# Print the symmetric difference
print("Symmetric Difference:", symmetric_difference)

Symmetric Difference: {1, 2, 3, 6, 7, 8}


- `set1 = {1, 2, 3, 4, 5}`: Here, we define the first set containing integers from 1 to 5.
- `set2 = {4, 5, 6, 7, 8}`: We define the second set containing integers that partially overlap with the first set.
- `symmetric_difference = set1 ^ set2`: The ^ operator is used to calculate the symmetric difference between two sets. It returns a new set containing elements that are in either of the sets, but not in their intersection.
- `print("Symmetric Difference:", symmetric_difference)`: Finally, we print out the symmetric difference set.

### 20. Update a set with elements from another set.

In [183]:
# Create the first set
set1 = {1, 2, 3}
print("Set 1:", set1)

# Create the second set
set2 = {3, 4, 5}
print("Set 2:", set2)

# Update set1 with elements from set2
set1.update(set2)
print("Updated Set 1:", set1)

Set 1: {1, 2, 3}
Set 2: {3, 4, 5}
Updated Set 1: {1, 2, 3, 4, 5}


- `set1 = {1, 2, 3}`: We create the first set named set1 with elements 1, 2, and 3.
- `print("Set 1:", set1)`: This line prints the contents of set1 which is {1, 2, 3}.
- `set2 = {3, 4, 5}`: We create the second set named set2 with elements 3, 4, and 5.
- `print("Set 2:", set2)`: This line prints the contents of set2 which is {3, 4, 5}.
- `set1.update(set2)`: The update() method is used to update set1 with the elements from set2. After this line, set1 will contain all unique elements from both set1 and set2.
- `print("Updated Set 1:", set1)`: This line prints the updated contents of set1, which will now be {1, 2, 3, 4, 5}.

### 21. Create a set of the first 5 prime numbers.

In [184]:
# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

# Create an empty set to store the prime numbers
prime_set = set()

# Initialize the number to start checking for primes
num = 2

# Loop until we have found the first 5 prime numbers
while len(prime_set) < 5:
    # Check if the current number is prime using the is_prime function
    if is_prime(num):
        # If the number is prime, add it to the prime_set
        prime_set.add(num)

    # Move on to the next number for the next iteration
    num += 1

# Print the set of prime numbers
print("Set of the first 5 prime numbers:", prime_set)

Set of the first 5 prime numbers: {2, 3, 5, 7, 11}


- We start by defining a function is_prime that checks if a given number is prime. It returns True if the number is prime and False otherwise.
- We create an empty set prime_set to store the first 5 prime numbers.
- We initialize the variable num to start checking for prime numbers, beginning with 2.
- We use a while loop to continue searching for prime numbers until we have found 5 of them.
- Inside the loop, we check if the current value of num is prime by calling the is_prime function. If it's prime, we add it to the prime_set.
- Regardless of whether the current num is prime or not, we increment num by 1 to move to the next number for the next iteration of the loop.
- Once we have found 5 prime numbers and the loop terminates, we print the set of prime numbers.

### 22. Check if two sets are identical.

In [185]:
# Step 1: Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {3, 1, 5, 2, 4}  # The order of elements doesn't matter in sets

# Step 2: Check if the sets are identical using the `==` operator
# Sets are unordered collections, so the order of elements doesn't matter.
# The `==` operator compares the content of the sets.
if set1 == set2:
    print("The sets are identical.")
else:
    print("The sets are not identical.")

The sets are identical.


- We define two sets, set1 and set2, containing the same integers but in different orders. Remember that sets are unordered, so the order of elements doesn't matter.
- We use the == operator to check if the content of set1 is the same as the content of set2. Since sets are unordered collections, the comparison considers the elements themselves, not their order. If the sets have the same elements, they are considered identical.
- If the sets are identical (meaning they have the same elements, regardless of order), the code inside the if block will execute, and the message "The sets are identical." will be printed. Otherwise, if the sets are not identical, the code inside the else block will execute, and the message "The sets are not identical." will be printed.

### 23. Create a frozen set

In [186]:
# Step 2: Define a list of elements that you want to include in the frozen set
elements = [1, 2, 3, 4, 5]

# Step 3: Create a frozen set using the 'frozenset' constructor and passing the list of elements
my_frozen_set = frozenset(elements)

# Step 4: Print the frozen set
print("Frozen Set:", my_frozen_set)

Frozen Set: frozenset({1, 2, 3, 4, 5})


- We start by importing the frozenset class from the collections module. The frozenset is an immutable version of a set, meaning its elements cannot be modified after creation.
- We define a list called elements that contains the integers from 1 to 5 that we want to include in the frozen set.
- Using the frozenset constructor, we create a frozen set named my_frozen_set by passing the elements list as an argument. This freezes the set, making it unchangeable.
- Finally, we print the frozen set using the print statement.

### 24. Check if a set is disjoint with another set.

In [187]:
# Step 1: Define the two sets you want to check for disjointness
set1 = {1, 2, 3, 4}
set2 = {5, 6, 7, 8}

# Step 2: Use the `isdisjoint()` method to check if the sets are disjoint
# The `isdisjoint()` method returns True if the sets have no common elements,
# and False if they have at least one common element.
disjoint_status = set1.isdisjoint(set2)

# Step 3: Print the result
print("Are the sets disjoint?", disjoint_status)

Are the sets disjoint? True


- We start by defining two sets, set1 and set2, which contain different elements. You can modify these sets with the elements you want to use for the check.
- The isdisjoint() method is called on set1 and is passed set2 as an argument. This method checks whether the sets have any elements in common.
- The result of the disjointness check is stored in the disjoint_status variable. If the sets are disjoint, disjoint_status will be True, and if they are not disjoint, it will be False.
- Finally, we use the print() function to display the result. It will print a message indicating whether the sets are disjoint or not based on the value of the disjoint_status variable.

### 25. Create a set of squares of numbers from 1 to 5.

In [188]:
# Step 1: Create an empty set to store the squares of numbers
squares_set = set()

# Step 2: Use a loop to iterate through numbers from 1 to 5
for num in range(1, 6):
    # Step 3: Calculate the square of the current number
    square = num ** 2

    # Step 4: Add the square to the set
    squares_set.add(square)

# Step 5: Print the set of squares
print(squares_set)

{1, 4, 9, 16, 25}


- We start by creating an empty set named squares_set using the set() constructor. This set will store the squares of numbers.
- We use a for loop to iterate through the numbers from 1 to 5 using the range(1, 6) function. The loop variable num will take values 1, 2, 3, 4, and 5 in each iteration.
- Inside the loop, we calculate the square of the current number using the exponentiation operator **. For example, if num is 2, then square will be calculated as 2 squared, which is 4.
- We add the calculated square to the squares_set using the .add() method of sets.
- After the loop completes, we print the squares_set, which will contain the squares of the numbers from 1 to 5.

### 26. Filter out all even numbers from a set.

In [189]:
# Step 1: Create a set with integers from 1 to 5
original_set = {1, 2, 3, 4, 5}

# Step 2: Initialize an empty set to store the filtered even numbers
even_numbers_set = set()

# Step 3: Iterate through each element in the original set
for num in original_set:
    # Step 4: Check if the current number is even (divisible by 2)
    if num % 2 == 0:
        # Step 5: If even, add it to the even_numbers_set
        even_numbers_set.add(num)

# Step 6: Print the original set and the set containing even numbers
print("Original Set:", original_set)
print("Even Numbers Set:", even_numbers_set)

Original Set: {1, 2, 3, 4, 5}
Even Numbers Set: {2, 4}


- We start by creating an original set containing integers from 1 to 5.
- We create an empty set called even_numbers_set to store the even numbers.
- We use a for loop to iterate through each element in the original_set.
- Inside the loop, we use the modulo operator % to check if the current number is even (divisible by 2).
- If the current number is even, we add it to the even_numbers_set using the add() method.
- Finally, we print both the original set and the set containing even numbers to see the results.

### 27. Multiply all elements in a set by 2.

In [190]:
# Create a set with integers from 1 to 5
original_set = {1, 2, 3, 4, 5}

# Initialize an empty set to store the multiplied elements
multiplied_set = set()

# Loop through each element in the original set
for num in original_set:
    # Multiply the current element by 2
    multiplied_num = num * 2

    # Add the multiplied element to the multiplied_set
    multiplied_set.add(multiplied_num)

# The original_set remains unchanged
print("Original Set:", original_set)

# Display the set with elements multiplied by 2
print("Multiplied Set:", multiplied_set)

Original Set: {1, 2, 3, 4, 5}
Multiplied Set: {2, 4, 6, 8, 10}


- We start by creating the original set containing integers from 1 to 5.
- We initialize an empty set called multiplied_set where we'll store the elements after they've been multiplied by 2.
- We then loop through each element in the original_set using a for loop.
- Inside the loop, we calculate the result of multiplying the current element num by 2, and store it in the variable multiplied_num.
- We add the multiplied_num to the multiplied_set using the .add() method.
- After the loop completes, the multiplied_set contains all the elements from the original set, each multiplied by 2.
- We print out the original_set to show that it remains unchanged.
- We print out the multiplied_set to display the set with elements multiplied by 2.

### 28. Create a set of random numbers.

In [191]:
# Step 1: Import the `random` module to generate random numbers
import random

# Step 2: Define the number of random numbers you want in the set
num_random_numbers = 5

# Step 3: Initialize an empty set to store the random numbers
random_number_set = set()

# Step 4: Use a loop to generate random numbers and add them to the set
for _ in range(num_random_numbers):
    # Generate a random integer using the `randint` function from the `random` module
    random_num = random.randint(1, 100)  # Generate a random number between 1 and 100
    # Add the random number to the set
    random_number_set.add(random_num)

# Step 5: Print the generated set of random numbers
print("Generated set of random numbers:", random_number_set)

Generated set of random numbers: {2, 37, 74, 43, 54}


- We begin by importing the random module, which provides functions for generating random numbers and performing other random-related operations.
- We define the variable num_random_numbers to specify how many random numbers we want in our set. You can change this value to generate a different number of random numbers.
- We initialize an empty set named random_number_set that will store our generated random numbers.
- We use a loop to generate random numbers and add them to the set. In each iteration of the loop, we generate a random integer using the random.randint(a, b) function, which generates a random integer between a and b (inclusive). We generate numbers between 1 and 100 in this example.
- Finally, we print the generated set of random numbers using the print function. The output will show the unique random numbers present in the set.


### 29. Check if a set is empty.

In [192]:
# Step 1: Create a set (you can replace this with your own set)
my_set = set()

# Step 2: Check if the set is empty using the 'if' statement
if not my_set:
    print("The set is empty.")
else:
    print("The set is not empty.")

The set is empty.


- We start by creating an empty set using the set() constructor. You can replace my_set with your own set if you want to check a different set.
- We use the if statement to check if the set is empty. The condition not my_set is True if the set is empty, and False if it contains any elements.
- If the condition is True, the program prints "The set is empty." If the condition is False, it prints "The set is not empty."

### 30. Create a nested set (hint: use frozenset).

In [193]:
# Step 1: Create the inner sets
set1 = {1, 2, 3, 4, 5}
set2 = {6, 7, 8, 9, 10}

# Step 2: Create frozensets from the inner sets
frozen_set1 = frozenset(set1)
frozen_set2 = frozenset(set2)

# Step 3: Create the nested set using the frozensets
nested_set = {frozen_set1, frozen_set2}

# Print the nested set
print("Nested Set:", nested_set)

Nested Set: {frozenset({1, 2, 3, 4, 5}), frozenset({6, 7, 8, 9, 10})}


- We import two sets, set1 and set2, containing integers from 1 to 5 and from 6 to 10, respectively.
- We then create two frozenset objects, frozen_set1 and frozen_set2, from set1 and set2. The use of frozenset ensures that the inner sets are immutable and can be used as elements of another set.
- Finally, we create the nested_set by adding the two frozenset objects into it. This creates a set containing two nested sets.
- We print the nested_set to see the result.

### 31.  Remove an element from a set using the discard method.

In [194]:
# Create a set with some elements
my_set = {1, 2, 3, 4, 5}

# Display the initial set
print("Initial set:", my_set)

# Define the element to be removed
element_to_remove = 3

# Use the discard() method to remove the element from the set
# If the element is not present in the set, discard() won't raise an error
my_set.discard(element_to_remove)

# Display the set after removing the element
print("Set after removing", element_to_remove, ":", my_set)

Initial set: {1, 2, 3, 4, 5}
Set after removing 3 : {1, 2, 4, 5}


- We start by creating a set named my_set with some elements {1, 2, 3, 4, 5}.
- We print the initial set using the print() function.
- We define the element we want to remove, in this case, element_to_remove is set to 3.
- We use the discard() method on the my_set set to remove the specified element (3). The discard() method removes the element if it's present in the set; otherwise, it does nothing without raising an error.
- We print the modified set after removing the element using the print() function.

### 32. Compare two sets.

In [195]:
# Step 1: Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Step 2: Use set operations to compare the sets
# Check if set1 is a subset of set2
is_subset = set1.issubset(set2)

# Check if set2 is a subset of set1
is_superset = set1.issuperset(set2)

# Find the intersection of the sets
intersection = set1.intersection(set2)

# Find the union of the sets
union = set1.union(set2)

# Find the elements that are in set1 but not in set2
difference1 = set1.difference(set2)

# Find the elements that are in set2 but not in set1
difference2 = set2.difference(set1)

# Step 3: Print the results
print("Set 1:", set1)
print("Set 2:", set2)
print("Is set1 a subset of set2?", is_subset)
print("Is set2 a subset of set1?", is_superset)
print("Intersection:", intersection)
print("Union:", union)
print("Elements in set1 but not in set2:", difference1)
print("Elements in set2 but not in set1:", difference2)

Set 1: {1, 2, 3, 4, 5}
Set 2: {4, 5, 6, 7, 8}
Is set1 a subset of set2? False
Is set2 a subset of set1? False
Intersection: {4, 5}
Union: {1, 2, 3, 4, 5, 6, 7, 8}
Elements in set1 but not in set2: {1, 2, 3}
Elements in set2 but not in set1: {8, 6, 7}


- We define two sets set1 and set2 containing some elements.
- We use various set operations to compare the two sets:
  - issubset() checks if set1 is a subset of set2.
  - issuperset() checks if set1 is a superset of set2.
  - intersection() finds the common elements between the sets.
  - union() finds the combined set of unique elements from both sets.
  - difference() finds the elements that are in the first set but not in the second set, and vice versa.
- We print out the original sets, the comparison results, the intersection, the union, and the differences.

### 33. Create a set from a string.

In [196]:
# Step 1: Define the input string
input_string = "hello"

# Step 2: Use the set() constructor to create a set from the characters in the string
char_set = set(input_string)

# Step 3: Print the resulting set
print(char_set)

{'h', 'e', 'l', 'o'}


- We start by defining an input string "hello".
- We use the set() constructor to create a set named char_set from the characters present in the input string. The set() constructor automatically eliminates duplicate characters since sets don't allow duplicates.
- Finally, we print the resulting set using the print() function. This will output a set containing the unique characters from the input string.

### 34. Convert a set of strings to a set of integers.

In [197]:
# Step 1: Create a set of strings
string_set = {"123", "456", "789"}

# Step 2: Initialize an empty set to store integers
integer_set = set()

# Step 3: Iterate through each string in the string set
for string in string_set:
    # Step 4: Convert the string to an integer using the int() function
    integer_value = int(string)

    # Step 5: Add the integer to the integer set
    integer_set.add(integer_value)

# Step 6: Print the original string set and the converted integer set
print("Original String Set:", string_set)
print("Converted Integer Set:", integer_set)

Original String Set: {'123', '789', '456'}
Converted Integer Set: {456, 123, 789}


- We start by creating a set of strings called string_set containing the strings "123", "456", and "789".
- We create an empty set called integer_set to store the converted integer values.
- We use a for loop to iterate through each string in the string_set.
- Inside the loop, we convert each string to an integer using the int() function and store it in the variable integer_value.
- We add the converted integer value to the integer_set using the add() method.
- After iterating through all the strings, we print both the original string_set and the converted integer_set.

### 35. Convert a set of integers to a set of strings.

In [198]:
# Step 1: Create a set of integers
integers_set = {1, 2, 3, 4, 5}

# Step 2: Initialize an empty set to store the strings
strings_set = set()

# Step 3: Iterate through each integer in the integers_set
for num in integers_set:
    # Step 4: Convert the integer to a string using the str() function
    num_str = str(num)

    # Step 5: Add the string representation to the strings_set
    strings_set.add(num_str)

# Step 6: Print the original integers_set and the converted strings_set
print("Original integers_set:", integers_set)
print("Converted strings_set:", strings_set)

Original integers_set: {1, 2, 3, 4, 5}
Converted strings_set: {'2', '4', '1', '5', '3'}


- We start by creating a set of integers called integers_set with a few example integers.
- We initialize an empty set called strings_set that we will use to store the string representations of the integers.
- We then iterate through each integer in the integers_set using a for loop.
- Inside the loop, we convert each integer to its string representation using the str() function. This is done in the num_str = str(num) line.
- We add the converted string num_str to the strings_set using the add() method.
- Finally, we print both the original integers_set and the converted strings_set to see the results.

### 36. Create a set from a tuple.

In [199]:
# Given tuple
input_tuple = (1, 2, 3, 2, 4, 5, 1)

# Step 1: Convert the tuple to a set
output_set = set(input_tuple)
# At this point, the set() function is used to convert the elements of the tuple into a set.
# Since sets only contain unique elements, duplicate values are automatically removed.

# Step 2: Print the resulting set
print(output_set)
# The set is now printed, and it will only contain the unique elements from the original tuple.

{1, 2, 3, 4, 5}


- We start by defining the input tuple called input_tuple containing some integer values.
- We use the set() function to convert the input_tuple into a set. This automatically removes duplicate values, so the resulting set will only contain unique elements.
- Finally, we print the output_set, which now holds the unique elements from the original tuple.

### 37. Convert a set to a tuple.

In [200]:
# Step 1: Create a set
input_set = {1, 2, 3, 4, 5}

# Step 2: Convert the set to a tuple
output_tuple = tuple(input_set)

# Step 3: Print the original set and the converted tuple
print("Original set:", input_set)
print("Converted tuple:", output_tuple)

Original set: {1, 2, 3, 4, 5}
Converted tuple: (1, 2, 3, 4, 5)


- We start by creating a set named input_set containing some example elements: 1, 2, 3, 4, and 5.
- We use the tuple() constructor to convert the input_set into a tuple. The tuple() constructor takes an iterable (like a set) as an argument and returns a tuple containing the elements of the iterable.
- We print out the original set and the converted tuple using the print() function. This helps us verify that the conversion was successful.

### 38. Find the maximum value in a set.

In [201]:
# Define a set with some values
my_set = {15, 7, 22, 13, 8}

# Initialize a variable to store the maximum value
max_value = None

# Iterate through each element in the set
for num in my_set:
    # Check if max_value is None (first iteration) or if the current number is greater than max_value
    if max_value is None or num > max_value:
        max_value = num  # Update max_value with the current number if it's greater

# Print the maximum value
print("Maximum value:", max_value)

Maximum value: 22


- We start by defining a set my_set containing some numeric values.
- We initialize a variable max_value to None. This variable will be used to keep track of the maximum value found so far.
- We use a for loop to iterate through each element (num) in the set my_set.
- Inside the loop, we have a conditional statement that checks two conditions:
- If max_value is None, it means we are in the first iteration, so we update max_value with the current number (num).
- If the current number (num) is greater than the current max_value, we update max_value with the current number (num).
- After the loop completes, we print the maximum value that was found.

### 39. Find the minimum value in a set.

In [202]:
# Create a sample set of numbers
number_set = {15, 8, 23, 4, 42, 11}

# Initialize a variable to store the minimum value
min_value = None

# Iterate through each element in the set
for num in number_set:
    # Check if min_value is None (first iteration) or if num is smaller than the current min_value
    if min_value is None or num < min_value:
        # Update min_value to the current num since it's smaller
        min_value = num

# Print the minimum value found in the set
print("The minimum value in the set is:", min_value)

The minimum value in the set is: 4


- We start by creating a sample set of numbers called number_set containing some integers.
- We initialize a variable min_value with the value None. This variable will store the minimum value found in the set.
- We use a for loop to iterate through each element in the number_set.
- Inside the loop, we check whether min_value is None (indicating the first iteration) or if the current num is smaller than the current min_value.
- If either condition is met, we update the value of min_value to the current num, since it's the smallest value found so far.
- Once the loop finishes, we print out the minimum value found in the set using the print statement.

### 40. Create a set from user input.

In [203]:
# Step 1: Initialize an empty set
user_set = set()

# Step 2: Get input from the user
print("Enter elements for the set (type 'done' to finish):")
while True:
    user_input = input("> ")  # Get input from the user

    if user_input.lower() == 'done':
        break  # Exit the loop if the user enters 'done'

    # Step 3: Add the user input to the set
    user_set.add(user_input)

# Step 4: Display the final set created from user input
print("Final set:", user_set)

Enter elements for the set (type 'done' to finish):


>  done


Final set: set()


- We start by initializing an empty set called user_set.
- We use a while loop to repeatedly get input from the user. The loop will continue until the user enters 'done'.
- Inside the loop, we use the add method to add each user input to the user_set. The .lower() method is used to convert the input to lowercase so that the comparison is case-insensitive.
- Once the user enters 'done', the loop is exited, and the code displays the final set that was created using the user inputs.

### 41. Check if the intersection of two sets is empty.

In [204]:
# Step 1: Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Step 2: Find the intersection of the two sets using the `intersection()` method
intersection_result = set1.intersection(set2)

# Step 3: Check if the intersection result is empty
if not intersection_result:
    print("The intersection of the two sets is empty.")
else:
    print("The intersection of the two sets is not empty.")

The intersection of the two sets is not empty.


- We start by defining two sets, set1 and set2, with some example elements. You can replace these sets with your own sets if needed.
- The intersection_result is obtained by using the intersection() method of the first set (set1). This method returns a new set containing elements that are present in both set1 and set2.
- We then use an if statement to check if the intersection_result is empty. The condition if not intersection_result: checks if the set is empty. If the condition is true, it means the intersection is empty, and we print the corresponding message. If the condition is false, it means the intersection is not empty, and we print the corresponding message.

### 42. Create a set of the first 5 Fibonacci numbers.

In [205]:
# Create a set to store the first 5 Fibonacci numbers
fibonacci_set = set()

# Initialize the first two Fibonacci numbers
a, b = 0, 1

# Loop to generate the first 5 Fibonacci numbers
for _ in range(6):
    # Add the current Fibonacci number to the set
    fibonacci_set.add(a)

    # Calculate the next Fibonacci number
    a, b = b, a + b

# Print the set of Fibonacci numbers
print("Set of the first 5 Fibonacci numbers:", fibonacci_set)

Set of the first 5 Fibonacci numbers: {0, 1, 2, 3, 5}


- We create an empty set fibonacci_set to store the first 5 Fibonacci numbers.
- We initialize two variables a and b to 0 and 1 respectively, as the first two Fibonacci numbers.
- We use a for loop to generate the first 5 Fibonacci numbers. The loop iterates 5 times.
- Inside the loop, we add the current value of a (which is a Fibonacci number) to the fibonacci_set.
- We update the values of a and b to calculate the next Fibonacci number. This is done by swapping the values: a becomes b and b becomes the sum of the previous a and b.
- Once the loop finishes, we print the set of the first 5 Fibonacci numbers.

### 43. Remove duplicates from a list using sets.

In [206]:
# Step 1: Define a list with duplicates
original_list = [2, 4, 6, 8, 4, 10, 6, 12, 14, 8]

# Step 2: Convert the list to a set
unique_set = set(original_list)
# Now, 'unique_set' contains only unique elements from 'original_list'

# Step 3: Convert the set back to a list
unique_list = list(unique_set)
# Now, 'unique_list' is a list containing only unique elements

# Step 4: Print the original list and the list with duplicates removed
print("Original List:", original_list)
print("List with Duplicates Removed:", unique_list)

Original List: [2, 4, 6, 8, 4, 10, 6, 12, 14, 8]
List with Duplicates Removed: [2, 4, 6, 8, 10, 12, 14]


- We start by defining an original_list that contains duplicate elements.
- We use the set() function to convert the original_list into a set. Sets are collections that automatically remove duplicate elements, so this step effectively removes duplicates from the list. The variable unique_set now contains only the unique elements from the original list.
- We convert the unique_set back into a list using the list() function. This step is necessary if you need the final result as a list.
- Finally, we print both the original list and the list with duplicates removed to see the difference.

### 44. Check if two sets have the same elements, regardless of their count.

In [207]:
def have_same_elements(set1, set2):
    # Convert the sets to lists and sort them
    sorted_list1 = sorted(list(set1))
    sorted_list2 = sorted(list(set2))

    # Compare the sorted lists to check if they are equal
    return sorted_list1 == sorted_list2

# Example sets
set1 = {1, 2, 3, 2, 1}
set2 = {3, 1, 2}

# Check if the sets have the same elements
result = have_same_elements(set1, set2)

# Print the result
if result:
    print("The sets have the same elements.")
else:
    print("The sets do not have the same elements.")

The sets have the same elements.


- We define a function have_same_elements that takes two sets (set1 and set2) as its arguments.
- Inside the function:
- We convert the sets to lists using list(set1) and list(set2) to make them sortable.
- We then sort both lists using the sorted function to ensure that the order of elements doesn't matter.
- We use the equality operator == to compare the sorted lists sorted_list1 and sorted_list2.
- The function returns True if the sorted lists are equal, indicating that the sets have the same elements (regardless of their count), and False otherwise.
- We define example sets set1 and set2 with elements that are the same but might be in different orders or have different counts.
- We call the have_same_elements function with set1 and set2 as arguments and store the result in the result variable.
- Finally, we print a message based on the value of result, indicating whether the sets have the same elements or not.

### 45. Create a set of the first `n` powers of 2

In [208]:
def generate_powers_of_2(n):
    # Initialize an empty set to store the powers of 2
    powers_of_2 = set()

    # Loop from 0 to n-1
    for i in range(n):
        # Calculate the current power of 2 using the exponentiation operator **
        power = 2 ** i

        # Add the current power of 2 to the set
        powers_of_2.add(power)

    # Return the set of powers of 2
    return powers_of_2

# Define the value of n
n = 5

# Call the function to generate the set of powers of 2
powers_set = generate_powers_of_2(n)

# Print the resulting set
print(powers_set)

{1, 2, 4, 8, 16}


- We define a function generate_powers_of_2 that takes an argument n, which represents the number of powers of 2 to generate.
- Inside the function, we initialize an empty set powers_of_2 to store the powers of 2.
- We use a for loop to iterate from 0 to n-1. In each iteration, we calculate the current power of 2 using the exponentiation operator **, where the exponent is i.
- The calculated power of 2 is added to the powers_of_2 set using the add() method.
- Once the loop is finished, the function returns the set powers_of_2 containing the generated powers of 2.
- Outside the function, we define the value of n as 5 (you can change this value to generate a different number of powers).
- We call the generate_powers_of_2 function with the value of n and store the resulting set in the powers_set variable.
- Finally, we print the powers_set to see the set of the first n powers of 2.

### 46. Find the common elements between a set and a list.

In [209]:
# Step 1: Define a set and a list
my_set = {3, 7, 9, 12, 15}
my_list = [7, 12, 5, 9]

# Step 2: Convert the list to a set for efficient comparison
list_to_set = set(my_list)

# Step 3: Initialize an empty list to store common elements
common_elements = []

# Step 4: Iterate through the elements in the set
for element in my_set:
    # Step 5: Check if the element is present in the converted set (list_to_set)
    if element in list_to_set:
        # Step 6: If the element is present in both the set and the list, add it to the common_elements list
        common_elements.append(element)

# Step 7: Print the common elements
print("Common elements:", common_elements)

Common elements: [7, 9, 12]


- We start by defining a set named my_set and a list named my_list that contain some elements.
- To efficiently compare the elements, we convert the list to a set using the set() constructor. This step helps in faster membership testing.
- We create an empty list called common_elements where we will store the elements that are common between the set and the list.
- We start iterating through the elements in the set using a for loop.
- Inside the loop, we check if the current element is present in the converted set (list_to_set) using the element in list_to_set syntax.
- If the element is found in both the set and the list, we append it to the common_elements list.
- After the loop is complete, we print the common_elements list which contains the common elements between the set and the list.

### 47. Create a set of the first `n` triangular numbers.:

Triangular numbers are a sequence of numbers that represent the number of dots in a triangular arrangement. The sequence starts with 1 and then each subsequent number is obtained by adding the next natural number.

Mathematically, the $n^{th}$ triangular number, denoted as $T_n$, is given by the formula:

$T_n$ $=$ $1+2+3+...+n=\frac {n*(n + 1)}{2}$

Visually, you can imagine triangular numbers by arranging dots in the shape of equilateral triangles:

```
   1       1 dot
   1 1      3 dots
   1 2 1     6 dots
   1 2 3 1   10 dots
```

In [210]:
def generate_triangular_numbers(n):
    triangular_numbers = set()  # Create an empty set to store the triangular numbers
    for i in range(1, n + 1):
        triangular_number = i * (i + 1) // 2  # Calculate the ith triangular number using the formula
        triangular_numbers.add(triangular_number)  # Add the calculated triangular number to the set
    return triangular_numbers

# Input the value of 'n'
n = int(input("Enter the value of n: "))

# Call the function to generate the set of first 'n' triangular numbers
triangular_set = generate_triangular_numbers(n)

# Display the set of triangular numbers
print(f"The set of the first {n} triangular numbers is:", triangular_set)

Enter the value of n:  10


The set of the first 10 triangular numbers is: {1, 3, 36, 6, 10, 45, 15, 21, 55, 28}


### 48. Check if a set contains another set as a subset.

In [211]:
# Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4}

# Check if set2 is a subset of set1
is_subset = set2.issubset(set1)

# Print the result
if is_subset:
    print("set2 is a subset of set1")
else:
    print("set2 is not a subset of set1")

set2 is a subset of set1


### 49. Create a set of alternating 1s and 0s of length `n`.

In [212]:
def create_alternating_set(n):
    # Initialize an empty set to store the alternating sequence.
    alternating_set = set()

    # Loop to generate alternating 1s and 0s.
    for i in range(n):
        # Alternate between adding 1 and 0 to the set based on whether i is even or odd.
        if i % 2 == 0:
            alternating_set.add(1)  # Add 1 if i is even.
        else:
            alternating_set.add(0)  # Add 0 if i is odd.

    return alternating_set

# Define the desired length of the alternating set.
length_n = 10

# Call the function to create the alternating set of length 'length_n'.
result = create_alternating_set(length_n)

# Print the resulting set.
print(result)

{0, 1}


### 50. Merge multiple sets into one.

In [213]:
# Step 1: Create multiple sets
set1 = {1, 2, 3}
set2 = {3, 4, 5}
set3 = {5, 6, 7}

# Step 2: Use the union() method to merge sets
merged_set = set1.union(set2, set3)

# Alternatively, you can use the | operator
# merged_set = set1 | set2 | set3

# Step 3: Print the merged set
print("Merged Set:", merged_set)

Merged Set: {1, 2, 3, 4, 5, 6, 7}
